# Generated by Django 5.2.12 on 2026-06-15 20:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0094_serviceordertask_payment_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Razão Social')),
                ('company_type', models.CharField(blank=True, choices=[('MEI', 'MEI'), ('LIMITED', 'LTDA'), ('INDIVIDUAL', 'Empresário Individual'), ('ASSOCIATION', 'Associação'), ('AUTONOMO', 'Autônomo')], max_length=15, verbose_name='Tipo de Empresa')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, verbose_name='CPF / CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone / Celular')),
                ('address_street', models.CharField(blank=True, max_length=255, verbose_name='Logradouro')),
                ('address_number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('address_neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('address_state', models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)')),
                ('address_zip', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('wallet_id', models.CharField(blank=True, help_text='ID da carteira no Asaas após aprovação', max_length=100, verbose_name='Wallet ID')),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox (Testes)'), ('PRODUCTION', 'Produção')], default='SANDBOX', max_length=15, verbose_name='Ambiente')),
                ('status', models.CharField(choices=[('NOT_CONFIGURED', 'Não Configurado'), ('PENDING_DOCS', 'Documentação Pendente'), ('UNDER_ANALYSIS', 'Em Análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='NOT_CONFIGURED', max_length=20, verbose_name='Status')),
                ('status_detail', models.TextField(blank=True, verbose_name='Detalhes do Status')),
                ('platform_split_type', models.CharField(choices=[('PERCENT', 'Percentual (%)'), ('FIXED', 'Valor Fixo (R$)')], default='PERCENT', max_length=10, verbose_name='Tipo de Split')),
                ('platform_split_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Valor do Split')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Gateway',
                'verbose_name_plural': 'Configurações de Gateway',
            },
        ),
        migrations.CreateModel(
            name='GatewayCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='ASAAS', max_length=20, verbose_name='Gateway')),
                ('external_id', models.CharField(help_text='ID da cobrança no gateway', max_length=100, unique=True, verbose_name='ID Externo')),
                ('method', models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto Bancário')], max_length=10, verbose_name='Método')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando Pagamento'), ('RECEIVED', 'Recebido'), ('CONFIRMED', 'Confirmado'), ('OVERDUE', 'Vencido'), ('REFUNDED', 'Estornado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('pix_qrcode', models.TextField(blank=True, verbose_name='QR Code PIX (Base64)')),
                ('pix_copy_paste', models.TextField(blank=True, verbose_name='PIX Copia e Cola')),
                ('pix_expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiração PIX')),
                ('boleto_url', models.URLField(blank=True, verbose_name='URL do Boleto')),
                ('boleto_barcode', models.CharField(blank=True, max_length=200, verbose_name='Linha Digitável')),
                ('boleto_bank_slip_url', models.URLField(blank=True, verbose_name='URL PDF Boleto')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('net_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Líquido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gateway_charges', to='services.installment', verbose_name='Parcela')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='pagamentos.gatewayconfig', verbose_name='Configuração')),
            ],
            options={
                'verbose_name': 'Cobrança no Gateway',
                'verbose_name_plural': 'Cobranças no Gateway',
                'ordering': ['-created_at'],
            },
        ),
    ]
