# Generated by Django 5.2.12 on 2026-06-15 21:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayconfig',
            name='income_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Exigido pelo Asaas para abertura de subconta', max_digits=12, verbose_name='Faturamento Mensal Estimado (R$)'),
        ),
    ]
