# Generated by Django 5.2.12 on 2026-06-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_gatewayconfig_subaccount_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaycharge',
            name='invoice_url',
            field=models.URLField(blank=True, verbose_name='URL da Fatura (Asaas)'),
        ),
        migrations.AlterField(
            model_name='gatewayconfig',
            name='wallet_id',
            field=models.CharField(blank=True, help_text='ID da carteira no Asaas após criação da subconta', max_length=100, verbose_name='Wallet ID'),
        ),
    ]
