# Generated by Django 5.2.12 on 2026-06-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_gatewaycharge_invoice_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayconfig',
            name='boleto_enabled',
            field=models.BooleanField(default=False, verbose_name='Boleto habilitado'),
        ),
        migrations.AddField(
            model_name='gatewayconfig',
            name='pix_enabled',
            field=models.BooleanField(default=True, verbose_name='PIX habilitado'),
        ),
    ]
