# Generated by Django 5.2.12 on 2026-06-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0005_gatewayconfig_pix_boleto_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayconfig',
            name='webhook_token',
            field=models.CharField(blank=True, help_text='Token cadastrado no painel Asaas ao registrar o webhook. O Asaas envia este valor no header asaas-access-token.', max_length=100, verbose_name='Token de Autenticação do Webhook'),
        ),
    ]
