# Generated by Django 5.2.12 on 2026-06-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0006_gatewayconfig_webhook_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaycharge',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Número visível no extrato do recebedor ao receber split', max_length=50, verbose_name='Número da Fatura (Asaas)'),
        ),
    ]
