# Generated by Django 5.2.12 on 2026-07-03 18:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0007_invoice_number_on_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingChargeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Regra')),
                ('default_method', models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto Bancário')], default='PIX', max_length=10, verbose_name='Método Padrão')),
                ('discount_type', models.CharField(choices=[('NONE', 'Sem desconto'), ('FIXED', 'Valor fixo (R$)'), ('PERCENTAGE', 'Percentual (%)')], default='NONE', max_length=15, verbose_name='Tipo de Desconto')),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Valor do Desconto')),
                ('discount_due_days', models.IntegerField(default=0, help_text='0 = desconto válido até o próprio vencimento', verbose_name='Prazo do Desconto (dias antes do vencimento)')),
                ('interest_monthly', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentual ao mês cobrado em caso de atraso. Ex: 1.00 = 1%/mês', max_digits=6, verbose_name='Juros por Atraso (% a.m.)')),
                ('fine_type', models.CharField(choices=[('NONE', 'Sem multa'), ('FIXED', 'Valor fixo (R$)'), ('PERCENTAGE', 'Percentual (%)')], default='NONE', max_length=15, verbose_name='Tipo de Multa')),
                ('fine_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Valor da Multa')),
                ('auto_send_to_gateway', models.BooleanField(default=False, help_text='Se ativo, dispara a cobrança no gateway assim que o billing for criado', verbose_name='Gerar cobrança automaticamente')),
                ('is_default', models.BooleanField(default=False, help_text='Aplicada automaticamente ao criar novos billings', verbose_name='Regra padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra de Cobrança',
                'verbose_name_plural': 'Regras de Cobrança',
                'ordering': ['name'],
            },
        ),
    ]
