# Generated by Django 5.2.12 on 2026-07-08 16:17

import django.db.models.deletion
from django.db import migrations, models


def backfill_default_payment_method(apps, schema_editor):
    BillingChargeConfig = apps.get_model('pagamentos', 'BillingChargeConfig')
    PaymentMethod = apps.get_model('services', 'PaymentMethod')
    for cfg in BillingChargeConfig.objects.all():
        method = PaymentMethod.objects.filter(
            tipo_provedor=cfg.default_method, ativo=True
        ).order_by('id').first()
        if method:
            cfg.default_payment_method_id = method.id
            cfg.save(update_fields=['default_payment_method'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0008_billingchargeconfig'),
        ('services', '0102_billing_charge_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingchargeconfig',
            name='default_payment_method',
            field=models.ForeignKey(blank=True, help_text='Método usado para gerar a cobrança no gateway — deve ser do tipo Pix ou Boleto', limit_choices_to={'ativo': True, 'tipo_provedor__in': ['PIX', 'BOLETO']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge_configs', to='services.paymentmethod', verbose_name='Método de Pagamento (gateway)'),
        ),
        migrations.RunPython(backfill_default_payment_method, noop_reverse),
        migrations.RemoveField(
            model_name='billingchargeconfig',
            name='default_method',
        ),
    ]
