# Generated by Django 5.2.12 on 2026-07-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0009_default_payment_method_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingchargeconfig',
            name='discount_applies_to_installments',
            field=models.BooleanField(default=False, help_text='Se desligado (padrão), o desconto por antecipação só é aplicado quando a cobrança for gerada à vista (1 parcela)', verbose_name='Desconto vale para parcelamento'),
        ),
    ]
