# Generated by Django 5.2.12 on 2026-07-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0010_discount_applies_to_installments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingchargeconfig',
            name='is_default',
        ),
    ]
