# Generated by Django 5.2.12 on 2026-07-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0011_remove_billingchargeconfig_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingchargeconfig',
            name='due_days',
            field=models.PositiveIntegerField(default=1, help_text='Dias após a geração da cobrança até o vencimento da 1ª parcela do boleto/pix.', verbose_name='Prazo de Vencimento (dias)'),
        ),
    ]
