# Generated by Django 5.2.12 on 2026-07-08 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0012_billingchargeconfig_due_days'),
        ('services', '0105_remove_financesettings_default_charge_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingchargeconfig',
            name='default_payment_method',
            field=models.ForeignKey(blank=True, help_text='Método de pagamento ao qual esta regra se aplica. Envio automático ao gateway só funciona para métodos do tipo Pix ou Boleto.', limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge_configs', to='services.paymentmethod', verbose_name='Método de Pagamento'),
        ),
    ]
