# Generated by Django 5.2.12 on 2026-07-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0013_alter_billingchargeconfig_default_payment_method'),
        ('services', '0106_paymentmethod_integra_gateway'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='billingchargeconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('default_payment_method',), name='unique_active_config_per_payment_method'),
        ),
    ]
