# Generated by Django 5.2.12 on 2026-07-13 21:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0014_unique_active_config_per_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaycharge',
            name='discount_due_days',
            field=models.IntegerField(default=0, help_text='0 = desconto válido até o próprio vencimento', verbose_name='Prazo do Desconto (dias antes do vencimento)'),
        ),
        migrations.AddField(
            model_name='gatewaycharge',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('NONE', 'Sem desconto'), ('FIXED', 'Valor fixo (R$)'), ('PERCENTAGE', 'Percentual (%)')], default='NONE', max_length=15, verbose_name='Tipo de Desconto'),
        ),
        migrations.AddField(
            model_name='gatewaycharge',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Valor do Desconto'),
        ),
    ]
