# Generated by Django 5.2.12 on 2026-09-08 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0015_gatewaycharge_discount_due_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayconfig',
            name='fee_terms_accepted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Aceite das tarifas em'),
        ),
        migrations.AddField(
            model_name='gatewayconfig',
            name='fee_terms_accepted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_fee_terms_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='Aceite das tarifas por'),
        ),
        migrations.AddField(
            model_name='gatewayconfig',
            name='fee_terms_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='Tarifas aceitas'),
        ),
    ]
