# Generated by Django 5.2.12 on 2026-09-28 22:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0016_gateway_fee_terms_acceptance'),
        ('services', '0121_salesettings_repeated_item_behavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaycharge',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='services.paymentmethod'),
        ),
        migrations.CreateModel(
            name='PosChargeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(choices=[('PROCESSING', 'Gerando'), ('UNKNOWN', 'Aguardando verificação'), ('REJECTED', 'Não emitida'), ('CREATED', 'Emitida')], default='PROCESSING', max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagamentos.gatewaycharge')),
                ('installment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pos_attempt', to='services.installment')),
            ],
        ),
    ]
