# Generated by Django 6.0.3 on 2026-03-20 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('INSPECTION', 'Em Vistoria'), ('BUDGETING', 'Aguardando Orçamento'), ('PENDING', 'Aguardando Aprovação'), ('APPROVED', 'Aprovado / Pendente Execução'), ('EXECUTING', 'Em Execução'), ('FINISHED', 'Finalizado'), ('WARRANTY', 'Em Garantia'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Descrição do Problema/Solicitação')),
                ('technical_notes', models.TextField(blank=True, verbose_name='Notas Técnicas/Vistoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Agendado para')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('client_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='services.property', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
        migrations.CreateModel(
            name='ServiceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='services/%Y/%m/%d/', verbose_name='Arquivo (Foto/Vídeo)')),
                ('media_type', models.CharField(choices=[('INSPECTION', 'Vistoria (Antes)'), ('EXECUTION', 'Execução (Durante)'), ('FINISHED', 'Finalizado (Depois)')], default='INSPECTION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='services.serviceorder')),
            ],
            options={
                'verbose_name': 'Mídia de Serviço',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Serviço/Material')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.serviceorder')),
            ],
            options={
                'verbose_name': 'Item de Serviço',
            },
        ),
    ]
