# Generated by Django 6.0.3 on 2026-03-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_professional_address_professional_base_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_alocations', to='services.professional')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.professionalrole', verbose_name='Função no Serviço')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='services.serviceorder')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Equipe do Serviço',
                'unique_together': {('service_order', 'professional')},
            },
        ),
    ]
