# Generated by Django 6.0.3 on 2026-03-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceorderteam'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceorderteam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='serviceorderteam',
            name='assignment_type',
            field=models.CharField(choices=[('BUDGET', 'Orçamento'), ('EXECUTION', 'Execução')], default='EXECUTION', max_length=20, verbose_name='Tipo de Designação'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('WAITING_BUDGET', 'Aguardando Orçamento'), ('BUDGET_SCHEDULED', 'Orçamento Agendado'), ('WAITING_APPROVAL', 'Aguardando Aprovação do Cliente'), ('APPROVED_WAITING_SCHEDULE', 'Aprovado - Aguardando Agendamento'), ('WAITING_EXECUTION', 'Aguardando Execução'), ('EXECUTING', 'Em Execução'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='WAITING_BUDGET', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceorderteam',
            unique_together={('service_order', 'professional', 'assignment_type')},
        ),
    ]
