# Generated by Django 6.0.3 on 2026-03-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_serviceorderteam_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('WAITING_BUDGET', 'Aguardando Orçamento'), ('BUDGET_SCHEDULED', 'Orçamento Agendado'), ('WAITING_APPROVAL', 'Aguardando Aprovação do Cliente'), ('APPROVED_WAITING_SCHEDULE', 'Aprovado - Aguardando Agendamento'), ('WAITING_EXECUTION', 'Aguardando Execução'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='WAITING_BUDGET', max_length=30, verbose_name='Status'),
        ),
    ]
