# Generated by Django 6.0.3 on 2026-03-23 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_serviceorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='scheduled_for',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='budget_scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visita de Orçamento Agendada para'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='execution_scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Execução de Serviço Agendada para'),
        ),
        migrations.CreateModel(
            name='ProfessionalScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Início do Bloqueio')),
                ('end_at', models.DateTimeField(verbose_name='Fim do Bloqueio')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo (Ex: Férias, Folga, Manutenção)')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Dia Inteiro')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='services.professional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Bloqueio de Agenda',
                'verbose_name_plural': 'Bloqueios de Agenda',
                'ordering': ['-start_at'],
            },
        ),
    ]
