# Generated by Django 6.0.3 on 2026-03-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_serviceorder_scheduled_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderteam',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Agendado para'),
        ),
    ]
