# Generated by Django 6.0.3 on 2026-03-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_serviceorderteam_scheduled_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceorderteam',
            unique_together={('service_order', 'professional')},
        ),
        migrations.RemoveField(
            model_name='serviceorderteam',
            name='assignment_type',
        ),
    ]
