# Generated by Django 6.0.3 on 2026-03-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_serviceorderteam_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorderteam',
            name='scheduled_at',
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('WAITING_VISIT', 'Aguardando visita inicial'), ('WAITING_BUDGET', 'Aguardando envio de orçamento'), ('BUDGET_SCHEDULED', 'Orçamento Agendado'), ('WAITING_APPROVAL', 'Aguardando Aprovação do Cliente'), ('APPROVED_WAITING_SCHEDULE', 'Aprovado - Aguardando Agendamento de execução'), ('WAITING_EXECUTION', 'Aguardando Execução'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='WAITING_BUDGET', max_length=30, verbose_name='Status'),
        ),
    ]
