# Generated by Django 6.0.3 on 2026-03-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_serviceorderteam_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceorderteam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='serviceorderteam',
            name='category',
            field=models.CharField(choices=[('INSPECTION', 'Vistoria/Orçamento'), ('EXECUTION', 'Execução/Instalação'), ('WARRANTY', 'Garantia')], default='EXECUTION', max_length=20, verbose_name='Categoria de Atuação'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceorderteam',
            unique_together={('service_order', 'professional', 'category')},
        ),
    ]
