# Generated by Django 6.0.3 on 2026-03-25 21:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_serviceorderteam_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemedia',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='servicemedia',
            name='service_order',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='budget_scheduled_at',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='execution_scheduled_at',
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='technical_notes',
            field=models.TextField(blank=True, verbose_name='Notas Técnicas Gerais'),
        ),
        migrations.CreateModel(
            name='ServiceOrderTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('BUDGET', 'Vistoria/Orçamento'), ('EXECUTION', 'Execução/Instalação'), ('WARRANTY', 'Garantia')], default='EXECUTION', max_length=20, verbose_name='Tipo de Etapa')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=20, verbose_name='Status')),
                ('scheduled_at', models.DateTimeField(verbose_name='Agendado para')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações Técnicas desta Etapa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='services.serviceorder', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Etapa de Serviço',
                'verbose_name_plural': 'Etapas de Serviço',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='serviceorderteam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='servicemedia',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='services.serviceordertask', verbose_name='Etapa/Tarefa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorderteam',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='services.serviceordertask', verbose_name='Etapa/Tarefa'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='serviceorderteam',
            unique_together={('task', 'professional')},
        ),
        migrations.RemoveField(
            model_name='serviceorderteam',
            name='category',
        ),
        migrations.RemoveField(
            model_name='serviceorderteam',
            name='service_order',
        ),
    ]
