# Generated by Django 6.0.3 on 2026-03-25 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_remove_servicemedia_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemedia',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='services.serviceordertask', verbose_name='Etapa/Tarefa'),
        ),
        migrations.AlterField(
            model_name='serviceorderteam',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='services.serviceordertask', verbose_name='Etapa/Tarefa'),
        ),
    ]
