# Generated by Django 5.2.12 on 2026-03-26 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_serviceorder_is_recurrent_alter_clientemail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='origin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Origem'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='originator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_orders', to='services.professional', verbose_name='Originador (Vendedor)'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='warranty_until',
            field=models.DateField(blank=True, null=True, verbose_name='Garantia Válida até'),
        ),
        migrations.AddField(
            model_name='serviceordertask',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor interno deste serviço/etapa', max_digits=10, null=True, verbose_name='Valor do Serviço'),
        ),
    ]
