# Generated by Django 5.2.12 on 2026-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_serviceorder_origin_date_serviceorder_originator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor total estimado para toda a OS', max_digits=10, null=True, verbose_name='Valor Estimado Total (R$)'),
        ),
    ]
