# Generated by Django 5.2.12 on 2026-03-26 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_serviceorder_estimated_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Deixe vazio para itens do orçamento geral. Preencha se o item foi adicionado durante uma etapa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.serviceordertask', verbose_name='Etapa Específica'),
        ),
    ]
