# Generated by Django 5.2.12 on 2026-03-31 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_add_company_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Escala (Ex: Padrão, Manhã)')),
            ],
            options={
                'verbose_name': 'Escala de Trabalho',
                'verbose_name_plural': 'Escalas de Trabalho',
            },
        ),
        migrations.AddField(
            model_name='professional',
            name='work_schedule',
            field=models.ForeignKey(blank=True, help_text='Selecione a escala padrão de disponibilidade deste colaborador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals', to='services.workschedule', verbose_name='Horário/Escala de Trabalho'),
        ),
        migrations.CreateModel(
            name='WorkScheduleDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('start_time', models.TimeField(verbose_name='Início')),
                ('end_time', models.TimeField(verbose_name='Fim')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='services.workschedule')),
            ],
            options={
                'verbose_name': 'Dia da Escala',
                'verbose_name_plural': 'Dias da Escala',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.DeleteModel(
            name='ProfessionalAvailability',
        ),
    ]
