# Generated by Django 5.2.12 on 2026-03-31 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_workschedule_professional_work_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto (R$)'),
        ),
        migrations.AddField(
            model_name='serviceordertask',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Aprovado pelo Cliente?'),
        ),
        migrations.AddField(
            model_name='serviceordertask',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PIX', 'PIX'), ('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito'), ('CASH', 'Dinheiro'), ('TRANSFER', 'Transferência Bancária'), ('BOLETO', 'Boleto')], max_length=20, null=True, verbose_name='Método de Pagamento Preferencial'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Estimado Total (R$)'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('WAITING_VISIT', 'Aguardando visita inicial'), ('BUDGET_SCHEDULED', 'Orçamento Agendado'), ('WAITING_APPROVAL', 'Orçamento Realizado - Aguardando Aprovação'), ('APPROVED_WAITING_SCHEDULE', 'Aprovado - Aguardando Agendamento'), ('WAITING_EXECUTION', 'Aguardando Execução'), ('WAITING_PAYMENT', 'Aguardando Pagamento'), ('PARTIAL_PAYMENT', 'Pagamento Parcial'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado'), ('WARRANTY', 'Em Garantia')], default='WAITING_VISIT', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='serviceordertask',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Serviço'),
        ),
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('payment_method', models.CharField(choices=[('PIX', 'PIX'), ('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito'), ('CASH', 'Dinheiro'), ('TRANSFER', 'Transferência Bancária'), ('BOLETO', 'Boleto')], max_length=20, verbose_name='Método de Pagamento')),
                ('paid_at', models.DateTimeField(verbose_name='Data do Pagamento')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.serviceorder', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-paid_at'],
            },
        ),
    ]
