# Generated by Django 5.2.12 on 2026-04-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceordertask',
            name='scheduled_end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Fim de Agendamento'),
        ),
    ]
