# Generated by Django 5.2.12 on 2026-04-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_serviceordertask_scheduled_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='property',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
    ]
