# Generated by Django 5.2.12 on 2026-04-13 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_alter_property_cep_alter_property_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_type', models.CharField(choices=[('DELAY', 'Atraso'), ('MATERIAL_MISSING', 'Falta de Material'), ('CUSTOMER_ABSENT', 'Cliente Ausente'), ('IMPEDIMENT', 'Impedimento no Local'), ('WARRANTY_ISSUE', 'Acionamento de Garantia'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='Tipo de Ocorrência')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registrada'), ('RESOLVED', 'Resolvida')], default='REGISTERED', max_length=20, verbose_name='Status')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação (Resolução)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='services.serviceordertask', verbose_name='Etapa/Tarefa')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
        migrations.AddField(
            model_name='servicemedia',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='services.occurrence', verbose_name='Ocorrência'),
        ),
    ]
