# Generated by Django 5.2.12 on 2026-04-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_occurrence_servicemedia_occurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceordertask',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Agendado'), ('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado'), ('NOT_EXECUTED', 'Não Executado')], default='SCHEDULED', max_length=20, verbose_name='Status'),
        ),
    ]
