# Generated by Django 5.2.12 on 2026-04-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_alter_serviceordertask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='category',
            field=models.CharField(choices=[('BLOCKING', 'Impeditiva'), ('MATERIAL_REQUEST', 'Solicitação de Material'), ('GENERAL', 'Ocorrência')], default='GENERAL', max_length=20, verbose_name='Categoria'),
        ),
    ]
