# Generated by Django 5.2.12 on 2026-04-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_occurrence_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='number',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True, verbose_name='Número da OS'),
        ),
    ]
