# Generated by Django 5.2.12 on 2026-04-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_serviceorder_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Número da OS'),
        ),
    ]
