# Generated by Django 6.0.3 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_product_serviceitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('UNIT', 'Unidade (un)'), ('METER', 'Metro (mt)')], default='UNIT', max_length=10, verbose_name='Unidade de Venda'),
        ),
    ]
