# Generated by Django 6.0.3 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_product_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Código'),
        ),
    ]
