# Generated by Django 5.2.12 on 2026-05-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='client_observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação para o Cliente'),
        ),
    ]
