# Generated by Django 5.2.12 on 2026-05-04 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_servicecategory_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_items', to='services.service', verbose_name='Serviço do Catálogo'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição Manual/Complemento'),
        ),
    ]
