# Generated by Django 5.2.12 on 2026-05-05 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_serviceitem_service_alter_serviceitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Item')),
                ('description', models.TextField(blank=True, verbose_name='Descrição/Instrução')),
                ('evidence_type', models.CharField(choices=[('TEXT', 'Texto'), ('PHOTO', 'Foto'), ('VIDEO', 'Vídeo')], default='TEXT', max_length=10, verbose_name='Tipo de Evidência')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Item de Check-list',
                'verbose_name_plural': 'Itens de Check-list',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskChecklistResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('text_response', models.TextField(blank=True, null=True, verbose_name='Resposta em Texto')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='checklist/photos/%Y/%m/%d/', verbose_name='Foto de Evidência')),
                ('video', models.FileField(blank=True, null=True, upload_to='checklist/videos/%Y/%m/%d/', verbose_name='Vídeo de Evidência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='services.servicechecklistitem', verbose_name='Item do Check-list')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='services.serviceordertask', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Resposta de Check-list',
                'verbose_name_plural': 'Respostas de Check-list',
                'unique_together': {('task', 'item')},
            },
        ),
    ]
