# Generated by Django 5.2.12 on 2026-05-05 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_servicechecklistitem_taskchecklistresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Modelo/Grupo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de Check-list',
                'verbose_name_plural': 'Modelos de Check-list',
            },
        ),
        migrations.RemoveField(
            model_name='taskchecklistresponse',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='taskchecklistresponse',
            name='video',
        ),
        migrations.AlterField(
            model_name='servicechecklistitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='services.service', verbose_name='Serviço'),
        ),
        migrations.CreateModel(
            name='ChecklistResponseMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='checklist/evidence/%Y/%m/%d/', verbose_name='Arquivo de Evidência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='services.taskchecklistresponse', verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Mídia de Check-list',
                'verbose_name_plural': 'Mídias de Check-list',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='checklist_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.checklisttemplate', verbose_name='Modelo de Check-list'),
        ),
        migrations.AddField(
            model_name='servicechecklistitem',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.checklisttemplate', verbose_name='Modelo'),
        ),
    ]
