# Generated by Django 5.2.12 on 2026-05-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_checklisttemplate_remove_taskchecklistresponse_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='chatwoot_budget_conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Conversa (Chatwoot)'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='chatwoot_budget_message_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Mensagem de Orçamento (Chatwoot)'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='client_budget_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cliente aprovou o orçamento em'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='client_budget_response',
            field=models.TextField(blank=True, null=True, verbose_name='Resposta do Cliente ao Orçamento'),
        ),
    ]
