# Generated by Django 5.2.12 on 2026-05-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_serviceorder_chatwoot_budget_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('WAITING_VISIT', 'Aguardando visita inicial'), ('BUDGET_SCHEDULED', 'Orçamento Agendado'), ('WAITING_APPROVAL', 'Orçamento Realizado - Aguardando Aprovação'), ('APPROVED_WAITING_SCHEDULE', 'Aprovado pelo cliente - Aguardando Agendamento de execução'), ('REJECTED_BY_CLIENT', 'Reprovado pelo cliente'), ('WAITING_EXECUTION', 'Aguardando Execução'), ('WAITING_PAYMENT', 'Aguardando Pagamento'), ('PARTIAL_PAYMENT', 'Pagamento Parcial'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado'), ('WARRANTY', 'Em Garantia')], default='WAITING_VISIT', max_length=30, verbose_name='Status'),
        ),
    ]
