# Generated by Django 5.2.12 on 2026-05-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_alter_serviceorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='client_budget_responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cliente respondeu o orçamento em'),
        ),
    ]
