# Generated by Django 5.2.12 on 2026-05-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_serviceorder_client_budget_responded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='pix_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cobrança/PIX enviada em'),
        ),
    ]
