# Generated by Django 5.2.12 on 2026-05-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0042_serviceorder_pix_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceordertask',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome de quem assinou'),
        ),
        migrations.AddField(
            model_name='serviceordertask',
            name='customer_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/', verbose_name='Assinatura do Cliente'),
        ),
    ]
