# Generated by Django 5.2.12 on 2026-05-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_serviceordertask_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceordertask',
            name='customer_signature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho da Assinatura'),
        ),
    ]
