# Generated by Django 5.2.12 on 2026-05-13 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0044_alter_serviceordertask_customer_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepayment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em'),
        ),
        migrations.AddField(
            model_name='servicepayment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
        migrations.AddField(
            model_name='servicepayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to='services.professional', verbose_name='Recebido por'),
        ),
        migrations.AddField(
            model_name='servicepayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente de Baixa'), ('CONFIRMED', 'Baixa Realizada')], default='CONFIRMED', max_length=20, verbose_name='Status'),
        ),
    ]
