# Generated by Django 5.2.12 on 2026-05-20 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0045_servicepayment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaProcessingJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_path', models.CharField(max_length=500, verbose_name='Arquivo bruto (local)')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Nome original')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='Content-Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('DONE', 'Concluído'), ('ERROR', 'Erro')], default='PENDING', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('result_media_type', models.CharField(blank=True, max_length=20, verbose_name='Tipo de mídia gerada')),
                ('result_media_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID da mídia gerada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_jobs', to='services.occurrence', verbose_name='Ocorrência')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_jobs', to='services.taskchecklistresponse', verbose_name='Resposta do Check-list')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_jobs', to='services.serviceordertask', verbose_name='Etapa/Tarefa')),
            ],
            options={
                'verbose_name': 'Job de Processamento de Mídia',
                'verbose_name_plural': 'Jobs de Processamento de Mídia',
                'ordering': ['created_at'],
            },
        ),
    ]
