# Generated by Django 5.2.12 on 2026-05-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0046_mediaprocessingjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='chatwoot_payment_receipt_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recibo/Avaliação enviada em'),
        ),
    ]
