# Generated by Django 5.2.12 on 2026-05-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0047_serviceorder_chatwoot_payment_receipt_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceordertask',
            name='send_whatsapp_confirmation',
            field=models.BooleanField(default=False, verbose_name='Enviar WhatsApp de Confirmação?'),
        ),
        migrations.AddField(
            model_name='serviceordertask',
            name='whatsapp_confirmation_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resposta recebida em'),
        ),
        migrations.AddField(
            model_name='serviceordertask',
            name='whatsapp_confirmation_status',
            field=models.CharField(blank=True, choices=[('SENT', 'Enviado'), ('WAITING', 'Aguardando Confirmação'), ('CONFIRMED', 'Confirmado'), ('RESCHEDULE', 'Reagendar')], max_length=20, null=True, verbose_name='Status da Confirmação WhatsApp'),
        ),
        migrations.AddField(
            model_name='serviceordertask',
            name='whatsapp_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notificação enviada em'),
        ),
        migrations.AddField(
            model_name='serviceordertask',
            name='whatsapp_response_content',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo da Resposta WhatsApp'),
        ),
    ]
