# Generated by Django 5.2.12 on 2026-05-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0051_product_current_stock_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem do Produto'),
        ),
    ]
