# Generated by Django 5.2.12 on 2026-05-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0052_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('UNIT', 'Unidade (un)'), ('METER', 'Metro (mt)'), ('M2', 'Metro Quadrado (m²)'), ('LITER', 'Litro (lt)'), ('KILO', 'Quilo (kg)')], default='UNIT', max_length=10, verbose_name='Unidade de Venda'),
        ),
    ]
