# Generated by Django 5.2.12 on 2026-05-27 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0053_alter_product_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Arquivo')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='Produtos Criados')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='Produtos Atualizados')),
                ('movements_count', models.PositiveIntegerField(default=0, verbose_name='Movimentações Geradas')),
                ('errors', models.TextField(blank=True, verbose_name='Erros/Alertas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Importação',
                'verbose_name_plural': 'Histórico de Importações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='import_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='services.importhistory', verbose_name='Origem (Importação)'),
        ),
    ]
