# Generated by Django 5.2.12 on 2026-05-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0054_importhistory_stockmovement_import_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
