# Generated by Django 5.2.12 on 2026-05-28 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0055_stockmovement_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='Linha')),
                ('identifier', models.CharField(max_length=255, verbose_name='Identificador (Código/Nome)')),
                ('action', models.CharField(max_length=50, verbose_name='Ação')),
                ('details', models.TextField(verbose_name='Detalhes da Alteração')),
                ('is_error', models.BooleanField(default=False, verbose_name='É Erro?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_logged', to='services.importhistory', verbose_name='Importação')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item da Importação',
                'verbose_name_plural': 'Itens da Importação',
                'ordering': ['row_number'],
            },
        ),
    ]
