# Generated by Django 5.2.12 on 2026-05-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0056_importitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistory',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Hash do Arquivo (Prevenção Duplicidade)'),
        ),
    ]
