# Generated by Django 5.2.12 on 2026-05-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0058_sale_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('PURCHASE', 'Compra'), ('SALE_OS', 'Venda OS'), ('SALE_DIRECT', 'Venda Direta (PDV)'), ('ADJUSTMENT', 'Ajuste de Estoque'), ('LOSS', 'Perda/Extravio'), ('RETURN', 'Devolução')], max_length=20, verbose_name='Motivo'),
        ),
    ]
