# Generated by Django 5.2.12 on 2026-05-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0059_alter_stockmovement_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aliquota_ibpt_est',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota IBPT Estadual (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='aliquota_ibpt_fed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota IBPT Federal (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='aliquota_ibpt_mun',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota IBPT Municipal (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Código de Barras (GTIN/EAN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='cest',
            field=models.CharField(blank=True, help_text='Código Especificador da Substituição Tributária (7 dígitos)', max_length=7, null=True, verbose_name='CEST'),
        ),
        migrations.AddField(
            model_name='product',
            name='cfop_padrao',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CFOP Padrão'),
        ),
        migrations.AddField(
            model_name='product',
            name='csosn',
            field=models.CharField(blank=True, help_text='Código de Situação da Operação no Simples Nacional', max_length=3, null=True, verbose_name='CSOSN'),
        ),
        migrations.AddField(
            model_name='product',
            name='cst_cofins',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='CST COFINS'),
        ),
        migrations.AddField(
            model_name='product',
            name='cst_icms',
            field=models.CharField(blank=True, help_text='Código de Situação Tributária do ICMS (Regime Normal)', max_length=2, null=True, verbose_name='CST ICMS'),
        ),
        migrations.AddField(
            model_name='product',
            name='cst_pis',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='CST PIS'),
        ),
        migrations.AddField(
            model_name='product',
            name='ncm',
            field=models.CharField(blank=True, help_text='Nomenclatura Comum do Mercosul (8 dígitos)', max_length=8, null=True, verbose_name='NCM'),
        ),
        migrations.AddField(
            model_name='product',
            name='origem_mercadoria',
            field=models.IntegerField(choices=[(0, '0 - Nacional'), (1, '1 - Estrangeira - Importação direta'), (2, '2 - Estrangeira - Adquirida no mercado interno'), (3, '3 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40%'), (4, '4 - Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos'), (5, '5 - Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%'), (6, '6 - Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX'), (7, '7 - Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX'), (8, '8 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70%')], default=0, verbose_name='Origem da Mercadoria'),
        ),
        migrations.AddField(
            model_name='property',
            name='ibge_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Código IBGE do Município'),
        ),
        migrations.AddField(
            model_name='sale',
            name='forma_pagamento_sefaz',
            field=models.CharField(choices=[('01', '01 - Dinheiro'), ('02', '02 - Cheque'), ('03', '03 - Cartão de Crédito'), ('04', '04 - Cartão de Débito'), ('05', '05 - Crédito Loja'), ('10', '10 - Vale Alimentação'), ('11', '11 - Vale Refeição'), ('12', '12 - Vale Presente'), ('13', '13 - Vale Combustível'), ('15', '15 - Boleto Bancário'), ('17', '17 - PIX'), ('90', '90 - Sem pagamento'), ('99', '99 - Outros')], default='01', max_length=2, verbose_name='Forma de Pagamento (SEFAZ)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='indicador_presenca',
            field=models.IntegerField(choices=[(1, '1 - Operação presencial'), (2, '2 - Operação não presencial, pela Internet'), (3, '3 - Operação não presencial, Teleatendimento'), (4, '4 - NFC-e em operação com entrega a domicílio'), (9, '9 - Operação não presencial, outros')], default=1, verbose_name='Indicador de Presença'),
        ),
        migrations.AddField(
            model_name='sale',
            name='modalidade_frete',
            field=models.IntegerField(choices=[(0, '0 - Contratação do Frete por conta do Remetente (CIF)'), (1, '1 - Contratação do Frete por conta do Destinatário (FOB)'), (2, '2 - Contratação do Frete por conta de Terceiros'), (3, '3 - Próprio por conta do Remetente'), (4, '4 - Próprio por conta do Destinatário'), (9, '9 - Sem Ocorrência de Transporte')], default=9, verbose_name='Modalidade do Frete'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cest_ato',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='CEST no ato'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cfop_aplicado',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CFOP Aplicado'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='ncm_ato',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='NCM no ato'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='origem_ato',
            field=models.IntegerField(blank=True, null=True, verbose_name='Origem no ato'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='vlr_tributos_ibpt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Tributos IBPT'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='cest_ato',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='CEST no ato'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='cfop_aplicado',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CFOP Aplicado'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='ncm_ato',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='NCM no ato'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='origem_ato',
            field=models.IntegerField(blank=True, null=True, verbose_name='Origem no ato'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='vlr_tributos_ibpt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Tributos IBPT'),
        ),
    ]
