# Generated by Django 5.2.12 on 2026-05-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0060_product_aliquota_ibpt_est_product_aliquota_ibpt_fed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='stock_lowered',
            field=models.BooleanField(default=False, verbose_name='Estoque Baixado'),
        ),
    ]
