# Generated by Django 5.2.12 on 2026-05-29 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0064_saleitem_discount_alter_saleitem_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('tipo_provedor', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('CREDIARIO', 'Crediário')], max_length=20, verbose_name='Tipo de Provedor')),
                ('tarifa_porcentagem', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tarifa (%)')),
                ('tarifa_fixa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarifa Fixa (R$)')),
                ('prazo_recebimento', models.IntegerField(default=0, verbose_name='Prazo de Recebimento (dias)')),
                ('codigo_sefaz', models.CharField(max_length=2, verbose_name='Código SEFAZ')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Método de Pagamento',
                'verbose_name_plural': 'Métodos de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Bruto')),
                ('valor_tarifa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Tarifa')),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Líquido')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('data_previsao', models.DateField(verbose_name='Previsão de Recebimento')),
                ('metodo_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.paymentmethod', verbose_name='Método de Pagamento')),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments', to='services.serviceorder', verbose_name='Ordem de Serviço')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Pagamento da Venda/OS',
                'verbose_name_plural': 'Pagamentos de Vendas/OS',
            },
        ),
    ]
