# Generated by Django 5.2.12 on 2026-05-31 04:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0065_paymentmethod_salepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Número da Venda'),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Número da Cobrança')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Bruto')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PARTIAL', 'Parcialmente Pago'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='services.client', verbose_name='Cliente')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing', to='services.sale', verbose_name='Venda')),
                ('service_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing', to='services.serviceorder', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Nº Parcela')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('OVERDUE', 'Atrasado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='services.billing', verbose_name='Cobrança')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.paymentmethod', verbose_name='Forma de Pagto')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['billing', 'installment_number'],
            },
        ),
    ]
