# Generated by Django 5.2.12 on 2026-05-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0066_sale_number_billing_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='surcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Acréscimo'),
        ),
    ]
