# Generated by Django 5.2.12 on 2026-05-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0067_sale_surcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado'), ('EM_ANDAMENTO', 'Em Andamento'), ('PRONTO', 'Pronto'), ('RECEBIDO', 'Recebido'), ('VENDA_AGENCIADA', 'Venda Agenciada'), ('DRAFT', 'Rascunho')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
    ]
