# Generated by Django 5.2.12 on 2026-05-31 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0069_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepayment',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_payments', to='services.installment', verbose_name='Parcela'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PARTIAL', 'Parcial'), ('PAID', 'Pago'), ('OVERDUE', 'Atrasado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
