# Generated by Django 5.2.12 on 2026-05-31 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0070_salepayment_installment_alter_installment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepayment',
            name='data_pagamento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Pagamento'),
        ),
    ]
