# Generated by Django 5.2.12 on 2026-06-01 06:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0071_alter_salepayment_data_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Inicial')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
            },
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('category_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], default='OUT', max_length=10, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('is_recurrent', models.BooleanField(default=False, verbose_name='Recorrência')),
                ('frequency', models.CharField(blank=True, choices=[('DAILY', 'Diária'), ('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quinzenal'), ('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], max_length=20, null=True, verbose_name='Frequência')),
                ('installments_count', models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.supplier', verbose_name='Fornecedor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.financialcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='expenses/%Y/%m/%d/', verbose_name='Arquivo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='services.expense', verbose_name='Despesa')),
            ],
            options={
                'verbose_name': 'Anexo de Despesa',
                'verbose_name_plural': 'Anexos de Despesa',
            },
        ),
        migrations.CreateModel(
            name='ExpenseInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.CharField(max_length=20, verbose_name='Número da Parcela')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da Parcela')),
                ('due_date', models.DateField(db_index=True, verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PARTIAL', 'Parcial'), ('PAID', 'Pago'), ('OVERDUE', 'Atrasado')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('payment_method', models.CharField(blank=True, choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('CREDIT_CARD', 'Cartão de Crédito'), ('CASH', 'Dinheiro'), ('TRANSFER', 'Transferência/TED')], max_length=20, null=True, verbose_name='Meio de Pagamento')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.bankaccount', verbose_name='Conta Bancária de Saída')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='services.expense', verbose_name='Despesa')),
            ],
            options={
                'verbose_name': 'Parcela de Despesa',
                'verbose_name_plural': 'Parcelas de Despesa',
                'ordering': ['due_date'],
            },
        ),
    ]
