# Generated by Django 5.2.12 on 2026-06-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0072_bankaccount_financialcategory_supplier_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcialmente Pago'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(blank=True, choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal'), ('ANUAL', 'Anual')], max_length=20, null=True, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='expenseinstallment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência/TED')], max_length=20, null=True, verbose_name='Meio de Pagamento'),
        ),
        migrations.AlterField(
            model_name='expenseinstallment',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='financialcategory',
            name='category_type',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], default='SAIDA', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mediaprocessingjob',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='category',
            field=models.CharField(choices=[('IMPEDITIVA', 'Impeditiva'), ('SOLICITACAO_MATERIAL', 'Solicitação de Material'), ('GERAL', 'Ocorrência')], default='GERAL', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='occurrence_type',
            field=models.CharField(choices=[('ATRASO', 'Atraso'), ('FALTA_MATERIAL', 'Falta de Material'), ('CLIENTE_AUSENTE', 'Cliente Ausente'), ('IMPEDIMENTO_LOCAL', 'Impedimento no Local'), ('ACIONAMENTO_GARANTIA', 'Acionamento de Garantia'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Tipo de Ocorrência'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='status',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('RESOLVIDA', 'Resolvida')], default='REGISTRADA', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('UNIDADE', 'Unidade (un)'), ('METRO', 'Metro (mt)'), ('M2', 'Metro Quadrado (m²)'), ('LITRO', 'Litro (lt)'), ('QUILO', 'Quilo (kg)')], default='UNIDADE', max_length=10, verbose_name='Unidade de Venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CARTAO_CREDITO', 'Cartão de Crédito')], max_length=20, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado'), ('EM_ANDAMENTO', 'Em Andamento'), ('PRONTO', 'Pronto'), ('RECEBIDO', 'Recebido'), ('VENDA_AGENCIADA', 'Venda Agenciada'), ('RASCUNHO', 'Rascunho'), ('FINALIZADA', 'Finalizada')], default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='servicechecklistitem',
            name='evidence_type',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('FOTO', 'Foto'), ('VIDEO', 'Vídeo')], default='TEXTO', max_length=10, verbose_name='Tipo de Evidência'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_VISITA', 'Aguardando visita inicial'), ('ORCAMENTO_AGENDADO', 'Orçamento Agendado'), ('ORCAMENTO_REALIZADO_AGUARDANDO_ENVIO', 'Orçamento realizado, aguardando envio'), ('AGUARDANDO_APROVACAO', 'Orçamento enviado - aguardando aprovação'), ('APROVADO_AGUARDANDO_AGENDAMENTO', 'Aprovado pelo cliente - Aguardando Agendamento de execução'), ('REPROVADO_PELO_CLIENTE', 'Reprovado pelo cliente'), ('AGUARDANDO_EXECUCAO', 'Aguardando Execução'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('PAGAMENTO_PARCIAL', 'Pagamento Parcial'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('GARANTIA', 'Em Garantia')], default='AGUARDANDO_VISITA', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='serviceordertask',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência Bancária'), ('BOLETO', 'Boleto')], max_length=20, null=True, verbose_name='Método de Pagamento Preferencial'),
        ),
        migrations.AlterField(
            model_name='serviceordertask',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('NAO_EXECUTADO', 'Não Executado')], default='AGENDADO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='serviceordertask',
            name='task_type',
            field=models.CharField(choices=[('ORCAMENTO', 'Vistoria/Orçamento'), ('EXECUCAO', 'Execução/Instalação'), ('GARANTIA', 'Garantia')], default='EXECUCAO', max_length=20, verbose_name='Tipo de Etapa'),
        ),
        migrations.AlterField(
            model_name='serviceordertask',
            name='whatsapp_confirmation_status',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('AGUARDANDO', 'Aguardando Confirmação'), ('CONFIRMADO', 'Confirmado'), ('REAGENDAR', 'Reagendar')], max_length=20, null=True, verbose_name='Status da Confirmação WhatsApp'),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='payment_method',
            field=models.CharField(choices=[('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência Bancária'), ('BOLETO', 'Boleto')], max_length=20, verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente de Baixa'), ('CONFIRMADO', 'Baixa Realizada')], default='CONFIRMADO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo de Movimento'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA_OS', 'Venda OS'), ('VENDA_DIRETA', 'Venda Direta (PDV)'), ('AJUSTE', 'Ajuste de Estoque'), ('PERDA', 'Perda/Extravio'), ('DEVOLUCAO', 'Devolução')], max_length=20, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COLABORADOR', 'Colaborador'), ('GERENTE', 'Gerente')], default='COLABORADOR', max_length=20, verbose_name='Papel/Função'),
        ),
    ]
