# Generated by Django 5.2.12 on 2026-06-01 12:54

from django.db import migrations


def ensure_column_widths(apps, schema_editor):
    """
    Garante fisicamente que colunas com valores PT-BR longos caibam antes da
    tradução dos dados. Necessário porque AlterField pode ser no-op quando o
    estado de migração já registra o max_length correto mas a coluna física
    ainda está estreita no PostgreSQL.
    Usa cursor direto para garantir execução imediata (não diferida).
    """
    if schema_editor.connection.vendor != 'postgresql':
        return

    # Colunas que podem receber valores > 20 chars do mapeamento de tradução.
    # serviceorder.status recebe até 36 chars (ORCAMENTO_REALIZADO_AGUARDANDO_ENVIO).
    # serviceordertask.status pode receber valores de OS por dados históricos misturados.
    columns_to_widen = [
        ('services_serviceorder', 'status', 50),
        ('services_serviceordertask', 'status', 50),
        ('services_serviceordertask', 'task_type', 50),
        ('services_serviceordertask', 'whatsapp_confirmation_status', 50),
        ('services_serviceordertask', 'payment_method', 50),
        ('services_installment', 'status', 50),
        ('services_billing', 'status', 50),
        ('services_sale', 'status', 50),
        ('services_occurrence', 'category', 50),
        ('services_occurrence', 'occurrence_type', 50),
        ('services_occurrence', 'status', 50),
        ('services_expenseinstallment', 'status', 50),
        ('services_expenseinstallment', 'payment_method', 50),
        ('services_mediaprocessingjob', 'status', 50),
        ('services_servicepayment', 'status', 50),
        ('services_servicepayment', 'payment_method', 50),
    ]
    with schema_editor.connection.cursor() as cursor:
        for table, column, width in columns_to_widen:
            cursor.execute(
                f'ALTER TABLE {table} ALTER COLUMN {column} TYPE VARCHAR({width})'
            )


def translate_data(apps, schema_editor):
    # Mapping for translation
    mapping = {
        'PENDING': 'PENDENTE',
        'PARTIAL': 'PARCIAL',
        'PAID': 'PAGO',
        'CANCELLED': 'CANCELADO',
        'FINISHED': 'FINALIZADO',
        'COMPLETED': 'CONCLUIDO',
        'OVERDUE': 'ATRASADO',
        'DRAFT': 'RASCUNHO',
        'APPROVED': 'APROVADO',
        'SCHEDULED': 'AGENDADO',
        'IN_PROGRESS': 'EM_ANDAMENTO',
        'BUDGET': 'ORCAMENTO',
        'EXECUTION': 'EXECUCAO',
        'WARRANTY': 'GARANTIA',
        'DAILY': 'DIARIA',
        'WEEKLY': 'SEMANAL',
        'BIWEEKLY': 'QUINZENAL',
        'MONTHLY': 'MENSAL',
        'YEARLY': 'ANUAL',
        'UNIT': 'UNIDADE',
        'METER': 'METRO',
        'LITER': 'LITRO',
        'KILO': 'QUILO',
        'IN': 'ENTRADA',
        'OUT': 'SAIDA',
        'PURCHASE': 'COMPRA',
        'SALE_OS': 'VENDA_OS',
        'SALE_DIRECT': 'VENDA_DIRETA',
        'ADJUSTMENT': 'AJUSTE',
        'LOSS': 'PERDA',
        'RETURN': 'DEVOLUCAO',
        'TEXT': 'TEXTO',
        'PHOTO': 'FOTO',
        'VIDEO': 'VIDEO',
        'SENT': 'ENVIADO',
        'WAITING': 'AGUARDANDO',
        'CONFIRMED': 'CONFIRMADO',
        'RESCHEDULE': 'REAGENDAR',
        'BLOCKING': 'IMPEDITIVA',
        'MATERIAL_REQUEST': 'SOLICITACAO_MATERIAL',
        'GENERAL': 'GERAL',
        'DELAY': 'ATRASO',
        'MATERIAL_MISSING': 'FALTA_MATERIAL',
        'CUSTOMER_ABSENT': 'CLIENTE_AUSENTE',
        'IMPEDIMENT': 'IMPEDIMENTO_LOCAL',
        'WARRANTY_ISSUE': 'ACIONAMENTO_GARANTIA',
        'OTHER': 'OUTRO',
        'REGISTERED': 'REGISTRADA',
        'RESOLVED': 'RESOLVIDA',
        'PROCESSING': 'PROCESSANDO',
        'DONE': 'CONCLUIDO',
        'ERROR': 'ERRO',
        'CASH': 'DINHEIRO',
        'CREDIT_CARD': 'CARTAO_CREDITO',
        'DEBIT_CARD': 'CARTAO_DEBITO',
        'TRANSFER': 'TRANSFERENCIA',
        # Casos específicos de ServiceOrder que mudei na mão no models.py
        'WAITING_VISIT': 'AGUARDANDO_VISITA',
        'BUDGET_SCHEDULED': 'ORCAMENTO_AGENDADO',
        'BUDGET_DONE_WAITING_SEND': 'ORCAMENTO_REALIZADO_AGUARDANDO_ENVIO',
        'WAITING_APPROVAL': 'AGUARDANDO_APROVACAO',
        'APPROVED_WAITING_SCHEDULE': 'APROVADO_AGUARDANDO_AGENDAMENTO',
        'REJECTED_BY_CLIENT': 'REPROVADO_PELO_CLIENTE',
        'WAITING_EXECUTION': 'AGUARDANDO_EXECUCAO',
        'WAITING_PAYMENT': 'AGUARDANDO_PAGAMENTO',
        'PARTIAL_PAYMENT': 'PAGAMENTO_PARCIAL',
    }

    # Modelos e Campos a traduzir
    targets = [
        ('services', 'ServiceOrder', 'status'),
        ('services', 'ServiceOrderTask', 'status'),
        ('services', 'ServiceOrderTask', 'task_type'),
        ('services', 'ServiceOrderTask', 'whatsapp_confirmation_status'),
        ('services', 'ServiceOrderTask', 'payment_method'),
        ('services', 'Installment', 'status'),
        ('services', 'Billing', 'status'),
        ('services', 'Sale', 'status'),
        ('services', 'Sale', 'payment_method'),
        ('services', 'StockMovement', 'movement_type'),
        ('services', 'StockMovement', 'reason'),
        ('services', 'Product', 'unit_type'),
        ('services', 'Occurrence', 'status'),
        ('services', 'Occurrence', 'category'),
        ('services', 'Occurrence', 'occurrence_type'),
        ('services', 'ServiceChecklistItem', 'evidence_type'),
        ('services', 'Expense', 'frequency'),
        ('services', 'ExpenseInstallment', 'status'),
        ('services', 'ExpenseInstallment', 'payment_method'),
        ('services', 'MediaProcessingJob', 'status'),
        ('services', 'User', 'role'),
        ('services', 'FinancialCategory', 'category_type'),
        ('services', 'ServicePayment', 'status'),
        ('services', 'ServicePayment', 'payment_method'),
    ]

    for app_label, model_name, field_name in targets:
        try:
            Model = apps.get_model(app_label, model_name)
            for old, new in mapping.items():
                Model.objects.filter(**{field_name: old}).update(**{field_name: new})
        except LookupError:
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0073_alter_billing_status_alter_expense_frequency_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_column_widths, migrations.RunPython.noop),
        migrations.RunPython(translate_data),
    ]
