# Generated by Django 5.2.12 on 2026-06-01 12:54

from django.db import migrations


def ensure_column_widths(apps, schema_editor):
    """
    Garante fisicamente que colunas varchar estreitas sejam alargadas antes da
    tradução dos dados. Usa information_schema para descobrir as colunas que
    existem e só executa ALTER TABLE nelas, evitando erros por tabelas ainda
    não criadas neste ponto da cadeia de migrations.
    Usa cursor direto (não schema_editor.execute) para execução imediata.
    """
    if schema_editor.connection.vendor != 'postgresql':
        return

    # Tabelas cujos campos de escolha serão traduzidos por translate_data.
    # Alargamos para varchar(100) todas as colunas varchar que ainda couberem
    # menos de 50 chars — qualquer valor do mapeamento PT-BR cabe em 100 chars.
    target_tables = [
        'services_serviceorder',
        'services_serviceordertask',
        'services_installment',
        'services_billing',
        'services_sale',
        'services_occurrence',
        'services_expenseinstallment',
        'services_mediaprocessingjob',
        'services_servicepayment',
        'services_stockmovement',
        'services_product',
        'services_servicechecklistitem',
        'services_expense',
        'services_user',
        'services_financialcategory',
    ]

    placeholders = ', '.join(['%s'] * len(target_tables))
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"""
            SELECT table_name, column_name
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND data_type = 'character varying'
              AND (character_maximum_length IS NULL OR character_maximum_length < 50)
              AND table_name IN ({placeholders})
            ORDER BY table_name, column_name
            """,
            target_tables,
        )
        columns = cursor.fetchall()

    with schema_editor.connection.cursor() as cursor:
        for table, column in columns:
            cursor.execute(
                f'ALTER TABLE "{table}" ALTER COLUMN "{column}" TYPE VARCHAR(100)'
            )


def translate_data(apps, schema_editor):
    # Mapping for translation
    mapping = {
        'PENDING': 'PENDENTE',
        'PARTIAL': 'PARCIAL',
        'PAID': 'PAGO',
        'CANCELLED': 'CANCELADO',
        'FINISHED': 'FINALIZADO',
        'COMPLETED': 'CONCLUIDO',
        'OVERDUE': 'ATRASADO',
        'DRAFT': 'RASCUNHO',
        'APPROVED': 'APROVADO',
        'SCHEDULED': 'AGENDADO',
        'IN_PROGRESS': 'EM_ANDAMENTO',
        'BUDGET': 'ORCAMENTO',
        'EXECUTION': 'EXECUCAO',
        'WARRANTY': 'GARANTIA',
        'DAILY': 'DIARIA',
        'WEEKLY': 'SEMANAL',
        'BIWEEKLY': 'QUINZENAL',
        'MONTHLY': 'MENSAL',
        'YEARLY': 'ANUAL',
        'UNIT': 'UNIDADE',
        'METER': 'METRO',
        'LITER': 'LITRO',
        'KILO': 'QUILO',
        'IN': 'ENTRADA',
        'OUT': 'SAIDA',
        'PURCHASE': 'COMPRA',
        'SALE_OS': 'VENDA_OS',
        'SALE_DIRECT': 'VENDA_DIRETA',
        'ADJUSTMENT': 'AJUSTE',
        'LOSS': 'PERDA',
        'RETURN': 'DEVOLUCAO',
        'TEXT': 'TEXTO',
        'PHOTO': 'FOTO',
        'VIDEO': 'VIDEO',
        'SENT': 'ENVIADO',
        'WAITING': 'AGUARDANDO',
        'CONFIRMED': 'CONFIRMADO',
        'RESCHEDULE': 'REAGENDAR',
        'BLOCKING': 'IMPEDITIVA',
        'MATERIAL_REQUEST': 'SOLICITACAO_MATERIAL',
        'GENERAL': 'GERAL',
        'DELAY': 'ATRASO',
        'MATERIAL_MISSING': 'FALTA_MATERIAL',
        'CUSTOMER_ABSENT': 'CLIENTE_AUSENTE',
        'IMPEDIMENT': 'IMPEDIMENTO_LOCAL',
        'WARRANTY_ISSUE': 'ACIONAMENTO_GARANTIA',
        'OTHER': 'OUTRO',
        'REGISTERED': 'REGISTRADA',
        'RESOLVED': 'RESOLVIDA',
        'PROCESSING': 'PROCESSANDO',
        'DONE': 'CONCLUIDO',
        'ERROR': 'ERRO',
        'CASH': 'DINHEIRO',
        'CREDIT_CARD': 'CARTAO_CREDITO',
        'DEBIT_CARD': 'CARTAO_DEBITO',
        'TRANSFER': 'TRANSFERENCIA',
        # Casos específicos de ServiceOrder que mudei na mão no models.py
        'WAITING_VISIT': 'AGUARDANDO_VISITA',
        'BUDGET_SCHEDULED': 'ORCAMENTO_AGENDADO',
        'BUDGET_DONE_WAITING_SEND': 'ORCAMENTO_REALIZADO_AGUARDANDO_ENVIO',
        'WAITING_APPROVAL': 'AGUARDANDO_APROVACAO',
        'APPROVED_WAITING_SCHEDULE': 'APROVADO_AGUARDANDO_AGENDAMENTO',
        'REJECTED_BY_CLIENT': 'REPROVADO_PELO_CLIENTE',
        'WAITING_EXECUTION': 'AGUARDANDO_EXECUCAO',
        'WAITING_PAYMENT': 'AGUARDANDO_PAGAMENTO',
        'PARTIAL_PAYMENT': 'PAGAMENTO_PARCIAL',
    }

    # Modelos e Campos a traduzir
    targets = [
        ('services', 'ServiceOrder', 'status'),
        ('services', 'ServiceOrderTask', 'status'),
        ('services', 'ServiceOrderTask', 'task_type'),
        ('services', 'ServiceOrderTask', 'whatsapp_confirmation_status'),
        ('services', 'ServiceOrderTask', 'payment_method'),
        ('services', 'Installment', 'status'),
        ('services', 'Billing', 'status'),
        ('services', 'Sale', 'status'),
        ('services', 'Sale', 'payment_method'),
        ('services', 'StockMovement', 'movement_type'),
        ('services', 'StockMovement', 'reason'),
        ('services', 'Product', 'unit_type'),
        ('services', 'Occurrence', 'status'),
        ('services', 'Occurrence', 'category'),
        ('services', 'Occurrence', 'occurrence_type'),
        ('services', 'ServiceChecklistItem', 'evidence_type'),
        ('services', 'Expense', 'frequency'),
        ('services', 'ExpenseInstallment', 'status'),
        ('services', 'ExpenseInstallment', 'payment_method'),
        ('services', 'MediaProcessingJob', 'status'),
        ('services', 'User', 'role'),
        ('services', 'FinancialCategory', 'category_type'),
        ('services', 'ServicePayment', 'status'),
        ('services', 'ServicePayment', 'payment_method'),
    ]

    for app_label, model_name, field_name in targets:
        try:
            Model = apps.get_model(app_label, model_name)
            for old, new in mapping.items():
                Model.objects.filter(**{field_name: old}).update(**{field_name: new})
        except LookupError:
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0073_alter_billing_status_alter_expense_frequency_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_column_widths, migrations.RunPython.noop),
        migrations.RunPython(translate_data),
    ]
