# Generated by Django 5.2.12 on 2026-06-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0074_traduzir_status_dados'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.CharField(choices=[('SIMPLES', 'Simples'), ('COM_VARIACOES', 'Com variações'), ('COM_COMPOSICAO', 'Com composição')], default='SIMPLES', max_length=20, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('PRODUTO', 'Produto'), ('SERVICO', 'Serviço'), ('PRODUTO_ACABADO', 'Produto acabado'), ('MATERIA_PRIMA', 'Matéria prima')], default='PRODUTO', max_length=20, verbose_name='Tipo'),
        ),
    ]
