# Generated by Django 5.2.12 on 2026-06-02 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0075_product_format_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_compositions', to='services.product', verbose_name='Componente')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='services.product', verbose_name='Produto Pai')),
            ],
            options={
                'verbose_name': 'Composição de Produto',
                'verbose_name_plural': 'Composições de Produtos',
                'unique_together': {('parent', 'component')},
            },
        ),
    ]
