# Generated by Django 5.2.12 on 2026-06-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0076_productcomposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço de Custo'),
        ),
        migrations.AddField(
            model_name='product',
            name='preco_custo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo Total'),
        ),
        migrations.AddField(
            model_name='product',
            name='preco_venda_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço Venda Total'),
        ),
    ]
