# Generated by Django 5.2.12 on 2026-06-04 04:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0077_product_preco_custo_product_preco_custo_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_generation', models.PositiveIntegerField(default=7, help_text='Quantos dias antes do vencimento o sistema deve gerar o registro de contas a pagar', verbose_name='Dias de antecedência para geração')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurações Financeiras',
                'verbose_name_plural': 'Configurações Financeiras',
            },
        ),
        migrations.AddField(
            model_name='expenseinstallment',
            name='recurrence_due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de Ocorrência da Recorrência'),
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('frequency', models.CharField(choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal'), ('ANUAL', 'Anual')], max_length=20, verbose_name='Frequência')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.financialcategory', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Regra de Recorrência',
                'verbose_name_plural': 'Regras de Recorrência',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='expenseinstallment',
            name='recurrence_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_installments', to='services.recurrencerule', verbose_name='Regra de Recorrência'),
        ),
    ]
