# Generated by Django 5.2.12 on 2026-06-04 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0078_financesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recurrence_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_templates', to='services.recurrencerule', verbose_name='Regra de Recorrência'),
        ),
    ]
