# Generated by Django 5.2.12 on 2026-06-04 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0079_expense_recurrence_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['name'], 'verbose_name': 'Conta Bancária', 'verbose_name_plural': 'Contas Bancárias'},
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('CORRENTE', 'Conta Corrente'), ('POUPANCA', 'Conta Poupança'), ('CAIXA', 'Caixa'), ('INVESTIMENTO', 'Investimento')], default='CORRENTE', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Pago')),
                ('payment_date', models.DateField(verbose_name='Data do Pagamento')),
                ('payment_method', models.CharField(blank=True, choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência/TED')], max_length=20, null=True, verbose_name='Meio de Pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_payments', to='services.bankaccount', verbose_name='Conta de Origem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.expenseinstallment', verbose_name='Parcela')),
            ],
            options={
                'verbose_name': 'Baixa de Parcela',
                'verbose_name_plural': 'Baixas de Parcela',
                'ordering': ['payment_date', 'created_at'],
            },
        ),
    ]
