# Generated by Django 5.2.12 on 2026-06-04 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0082_expense_document_ref_and_payment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Limite de Crédito (R$)'),
        ),
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Profundidade (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque Mínimo'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Peso Bruto (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Largura (cm)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comissão do Vendedor (%)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro Entrega'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP Entrega'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade Entrega'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento Entrega'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de Entrega'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Destinatário'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro Entrega'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Entrega'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Entrega'),
        ),
        migrations.AddField(
            model_name='sale',
            name='external_po_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Pedido do Cliente (PO)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='notes_customer',
            field=models.TextField(blank=True, null=True, verbose_name='Observações para o Cliente'),
        ),
        migrations.AddField(
            model_name='sale',
            name='notes_internal',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Internas'),
        ),
        migrations.AddField(
            model_name='sale',
            name='stock_reduced',
            field=models.BooleanField(default=False, verbose_name='Estoque Baixado'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cost_price_ato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Custo no ato'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Variação (ex: Azul P, Vermelho GG)')),
                ('code', models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Código')),
                ('barcode', models.CharField(blank=True, max_length=14, null=True, verbose_name='EAN/Código de Barras')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diferença de Preço (R$)')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque Atual')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque Mínimo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='services.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Variação de Produto',
                'verbose_name_plural': 'Variações de Produto',
            },
        ),
        migrations.AddField(
            model_name='saleitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.productvariant', verbose_name='Variação'),
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Motivo da Devolução')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('total_refund', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total Devolvido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='services.sale', verbose_name='Venda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Devolução de Venda',
                'verbose_name_plural': 'Devoluções de Venda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Devolvida')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Restituído')),
                ('restock', models.BooleanField(default=True, verbose_name='Retornar ao Estoque')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.saleitem', verbose_name='Item da Venda')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.salereturn', verbose_name='Devolução')),
            ],
            options={
                'verbose_name': 'Item da Devolução',
                'verbose_name_plural': 'Itens da Devolução',
            },
        ),
    ]
