# Generated by Django 5.2.12 on 2026-06-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0083_client_credit_limit_product_depth_product_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_trigger_status', models.CharField(choices=[('MANUAL', 'Somente Manual (não gerar automaticamente)'), ('EM_ANDAMENTO', 'Em Andamento'), ('PRONTO', 'Pronto'), ('ATENDIDO', 'Atendido'), ('RECEBIDO', 'Recebido'), ('VENDA_AGENCIADA', 'Venda Agenciada'), ('FINALIZADA', 'Finalizada')], default='FINALIZADA', max_length=20, verbose_name='Gerar cobrança automática quando a venda atingir o status')),
            ],
            options={
                'verbose_name': 'Configurações de Vendas',
                'verbose_name_plural': 'Configurações de Vendas',
            },
        ),
    ]
