# Generated by Django 5.2.12 on 2026-06-05 16:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0084_add_sale_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('icon', models.CharField(blank=True, default='tool', max_length=50, verbose_name='Ícone (Lucide)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Equipamento',
                'verbose_name_plural': 'Categorias de Equipamentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome / Identificação')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Nº de Série')),
                ('notes', models.TextField(blank=True, verbose_name='Observações Técnicas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='services.property', verbose_name='Imóvel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='services.assetcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Equipamento / Bem',
                'verbose_name_plural': 'Equipamentos / Bens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal (R$)')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Comissão do Técnico (%)')),
                ('frequency', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='SEMANAL', max_length=20, verbose_name='Frequência')),
                ('visit_days', models.JSONField(default=list, verbose_name='Dias de Visita')),
                ('description', models.TextField(blank=True, verbose_name='Descrição / Observações')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término (opcional)')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('PAUSADO', 'Pausado'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='services.asset', verbose_name='Equipamento')),
                ('primary_technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_maintenance_contracts', to='services.professional', verbose_name='Técnico Titular')),
            ],
            options={
                'verbose_name': 'Contrato de Manutenção',
                'verbose_name_plural': 'Contratos de Manutenção',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMonthlyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='Mês')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADO', 'Aprovado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Fechamento Mensal de Manutenção',
                'verbose_name_plural': 'Fechamentos Mensais de Manutenção',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Data Agendada')),
                ('external_technician_name', models.CharField(blank=True, max_length=255, verbose_name='Técnico Externo (nome)')),
                ('is_coverage', models.BooleanField(default=False, verbose_name='É Cobertura?')),
                ('coverage_receives_commission', models.BooleanField(default=False, verbose_name='Substituto Recebe Comissão?')),
                ('is_extra', models.BooleanField(default=False, verbose_name='Visita Extra (não gera comissão)')),
                ('check_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Check-in')),
                ('check_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Check-out')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='services.maintenancecontract', verbose_name='Contrato')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_visits_executed', to='services.professional', verbose_name='Técnico Executante')),
            ],
            options={
                'verbose_name': 'Visita de Manutenção',
                'verbose_name_plural': 'Visitas de Manutenção',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceClosingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de Comissão (R$)')),
                ('visits_count', models.PositiveIntegerField(default=0, verbose_name='Visitas Realizadas')),
                ('detail', models.JSONField(default=list, verbose_name='Detalhamento')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_closing_entries', to='services.professional', verbose_name='Técnico')),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='services.maintenancemonthlyclosing', verbose_name='Fechamento')),
            ],
            options={
                'verbose_name': 'Entrada de Fechamento',
                'verbose_name_plural': 'Entradas de Fechamento',
                'unique_together': {('closing', 'technician')},
            },
        ),
    ]
