# Generated by Django 5.2.12 on 2026-06-05 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0085_add_maintenance_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceVisitMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='maintenance_media/%Y/%m/', verbose_name='Arquivo')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='services.maintenancevisit', verbose_name='Visita')),
            ],
            options={
                'verbose_name': 'Mídia da Visita de Manutenção',
                'verbose_name_plural': 'Mídias das Visitas de Manutenção',
                'ordering': ['created_at'],
            },
        ),
    ]
