# Generated by Django 5.2.12 on 2026-06-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0086_add_maintenance_visit_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque Máximo'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='saldo_apos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo Após'),
        ),
    ]
