# Generated by Django 5.2.12 on 2026-06-10 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0087_stock_min_max_saldo_apos'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='services.serviceordertask', verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='serviceordertask',
            name='requires_client_approval',
            field=models.BooleanField(default=False, verbose_name='Requer Aprovação do Cliente?'),
        ),
        migrations.AddField(
            model_name='serviceordertask',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Etapa (R$)'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='service_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='services.serviceorder', verbose_name='Ordem de Serviço'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_VISITA', 'Aguardando visita inicial'), ('ORCAMENTO_AGENDADO', 'Orçamento Agendado'), ('ORCAMENTO_REALIZADO_AGUARDANDO_ENVIO', 'Orçamento realizado, aguardando envio'), ('AGUARDANDO_APROVACAO', 'Orçamento enviado - aguardando aprovação'), ('APROVADO_AGUARDANDO_AGENDAMENTO', 'Aprovado pelo cliente - Aguardando Agendamento de execução'), ('REPROVADO_PELO_CLIENTE', 'Reprovado pelo cliente'), ('AGUARDANDO_EXECUCAO', 'Aguardando Execução'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('PAGAMENTO_PARCIAL', 'Pagamento Parcial'), ('FINALIZADO', 'Finalizado'), ('CONCLUIDA', 'Concluída'), ('CANCELADO', 'Cancelado'), ('GARANTIA', 'Em Garantia')], default='AGUARDANDO_VISITA', max_length=50, verbose_name='Status'),
        ),
    ]
