# Generated by Django 5.2.12 on 2026-06-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0088_task_value_billing_per_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='service_type',
            field=models.CharField(blank=True, choices=[('INSTALACAO', 'Instalação'), ('MANUTENCAO_CORRETIVA', 'Manutenção Corretiva'), ('MANUTENCAO_PREVENTIVA', 'Manutenção Preventiva')], max_length=30, null=True, verbose_name='Tipo de OS'),
        ),
    ]
