# Generated by Django 5.2.12 on 2026-06-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0089_add_service_type_to_service_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='enable_commission',
            field=models.BooleanField(default=False, help_text='Quando ativo, exibe o relatório de comissões por etapa no painel financeiro.', verbose_name='Habilitar módulo de comissão'),
        ),
        migrations.AlterField(
            model_name='serviceordertask',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('PARCIALMENTE_EXECUTADO', 'Parcialmente Executado'), ('CANCELADO', 'Cancelado'), ('NAO_EXECUTADO', 'Não Executado')], default='AGENDADO', max_length=30, verbose_name='Status'),
        ),
    ]
