# Generated by Django 5.2.12 on 2026-06-13 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0091_push_notification_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='auto_billing_on_task_completion',
            field=models.BooleanField(default=True, help_text='Quando ativo, uma cobrança é criada automaticamente ao concluir etapas de Execução, Garantia ou Retorno com valor > 0.', verbose_name='Gerar cobrança automaticamente ao concluir etapa'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='cobrar_cliente',
            field=models.BooleanField(default=True, verbose_name='Cobrar do cliente'),
        ),
        migrations.AddField(
            model_name='serviceordertask',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuations', to='services.serviceordertask', verbose_name='Etapa de Origem'),
        ),
        migrations.AlterField(
            model_name='serviceordertask',
            name='task_type',
            field=models.CharField(choices=[('ORCAMENTO', 'Vistoria/Orçamento'), ('EXECUCAO', 'Execução/Instalação'), ('GARANTIA', 'Garantia'), ('RETORNO', 'Retorno')], default='EXECUCAO', max_length=20, verbose_name='Tipo de Etapa'),
        ),
    ]
