# Generated by Django 5.2.12 on 2026-06-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0095_serviceorder_public_token'),
        ('services', '0095_serviceordertask_discount'),
    ]

    operations = [
    ]
