# Generated by Django 5.2.12 on 2026-06-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0096_merge_20260623_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='tarifa_minima',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Se a tarifa percentual resultar em valor menor que este, aplica este mínimo.', max_digits=10, verbose_name='Tarifa Mínima (R$)'),
        ),
    ]
