# Generated by Django 5.2.12 on 2026-06-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0098_billing_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='budget_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Orçamento enviado em'),
        ),
    ]
