# Generated by Django 5.2.12 on 2026-06-27 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0099_add_budget_sent_at_to_serviceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_registered', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por'),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_source',
            field=models.CharField(choices=[('ADMIN', 'Usuário do sistema'), ('PUBLIC', 'Página pública')], default='ADMIN', max_length=10, verbose_name='Origem do cadastro'),
        ),
    ]
