# Generated by Django 5.2.12 on 2026-06-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0100_add_registration_source_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepayment',
            name='is_gateway_auto',
            field=models.BooleanField(default=False, help_text='True quando gerado automaticamente pelo webhook do gateway', verbose_name='Baixa Automática (Gateway)'),
        ),
    ]
