# Generated by Django 5.2.12 on 2026-07-03 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0008_billingchargeconfig'),
        ('services', '0101_salepayment_is_gateway_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='charge_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='pagamentos.billingchargeconfig', verbose_name='Regra de Cobrança'),
        ),
    ]
