# Generated by Django 5.2.12 on 2026-07-08 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0010_discount_applies_to_installments'),
        ('services', '0102_billing_charge_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='default_charge_config',
            field=models.ForeignKey(blank=True, help_text='Regra (desconto, juros, multa e envio automático ao gateway) aplicada às cobranças geradas automaticamente ao concluir etapas. Se vazio, usa a regra marcada como padrão.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_settings', to='pagamentos.billingchargeconfig', verbose_name='Regra de cobrança para faturamento automático'),
        ),
    ]
