# Generated by Django 5.2.12 on 2026-07-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0103_financesettings_default_charge_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceordertask',
            name='skip_auto_billing',
            field=models.BooleanField(default=False, help_text='Quando marcado, a conclusão desta etapa não dispara a geração automática de cobrança (mesmo com o faturamento automático ativo em Configurações Financeiras). Use quando o cliente pagará esta etapa parcelado — gere a cobrança manualmente depois.', verbose_name='Não gerar cobrança automática ao concluir'),
        ),
    ]
