# Generated by Django 5.2.12 on 2026-07-08 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0104_serviceordertask_skip_auto_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financesettings',
            name='default_charge_config',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='client_payment_method',
            field=models.ForeignKey(blank=True, help_text='Preferência informada pelo cliente na aprovação do orçamento; usada como padrão para novas etapas faturáveis desta OS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders', to='services.paymentmethod', verbose_name='Método de Pagamento Escolhido pelo Cliente'),
        ),
    ]
