# Generated by Django 5.2.12 on 2026-07-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0105_remove_financesettings_default_charge_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='integra_gateway',
            field=models.BooleanField(default=False, help_text='Marque apenas se este método for de fato processado automaticamente pelo gateway (Asaas) — ex: Pix automático via Asaas. Não marque para Pix manual via chave/CNPJ ou outros recebimentos que não passam pelo gateway.', verbose_name='Integra com Gateway de Pagamento'),
        ),
    ]
