# Generated by Django 5.2.12 on 2026-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0107_sale_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='discount_deadline',
            field=models.DateField(blank=True, help_text='Data até a qual o desconto informado é válido. Uso apenas informativo em mensagens.', null=True, verbose_name='Data Limite para Desconto'),
        ),
        migrations.AddField(
            model_name='billing',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentual de juros de mora informativo, exibido em mensagens (não é aplicado automaticamente ao saldo devedor).', max_digits=5, verbose_name='Juros (%)'),
        ),
    ]
