# Generated by Django 5.2.12 on 2026-07-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0108_billing_discount_deadline_billing_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='codigo_tributacao_nacional_iss',
            field=models.CharField(blank=True, help_text='Código de tributação nacional do ISS (padrão NFSe Nacional) para este serviço. Se vazio, a emissão de NFSe usa o código padrão configurado na integração fiscal.', max_length=6, verbose_name='Código de Tributação Nacional do ISS'),
        ),
    ]
