# Generated by Django 5.2.12 on 2026-07-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0109_service_codigo_tributacao_nacional_iss'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='codigo_tributacao_municipal_iss',
            field=models.CharField(blank=True, help_text='Código de tributação municipal do ISS (tabela própria da prefeitura, distinto do código nacional). Se vazio, a emissão de NFSe usa o código padrão configurado na integração fiscal.', max_length=3, verbose_name='Código de Tributação Municipal do ISS'),
        ),
    ]
