# Generated by Django 5.2.12 on 2026-07-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0110_service_codigo_tributacao_municipal_iss'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='codigo_indicador_operacao',
            field=models.CharField(blank=True, help_text='Indicador de operação da Reforma Tributária (IBS/CBS) — tabela do Anexo VIII (correlação item LC 116 x NBS x cIndOp x cClassTrib) do Comitê Gestor da NFS-e. Se vazio, a emissão de NFSe usa o código padrão configurado na integração fiscal.', max_length=6, verbose_name='Código Indicador de Operação (cIndOp)'),
        ),
    ]
