# Generated by Django 5.2.12 on 2026-07-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0111_service_codigo_indicador_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='codigo_nbs',
            field=models.CharField(blank=True, help_text='Código da Nomenclatura Brasileira de Serviços (9 dígitos, sem pontos — ex: 1.0105.30.00 vira 010530000), exigido pela NFSe Nacional junto com o grupo IBS/CBS (Reforma Tributária). Consulte o Anexo VIII do Comitê Gestor da NFS-e — o item LC 116 não define um único NBS, é uma escolha por tipo específico de serviço prestado. Se vazio, a emissão de NFSe usa o código padrão configurado na integração fiscal.', max_length=9, verbose_name='Código NBS'),
        ),
    ]
