# Generated by Django 5.2.12 on 2026-07-24 15:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0112_service_codigo_nbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='discount_deadline',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='interest',
        ),
        migrations.AddField(
            model_name='installment',
            name='discount_deadline',
            field=models.DateField(blank=True, help_text='due_date - discount_due_days, calculado na criação da parcela. Nulo se não há desconto.', null=True, verbose_name='Data Limite do Desconto'),
        ),
        migrations.AddField(
            model_name='installment',
            name='discount_due_days',
            field=models.IntegerField(default=0, verbose_name='Prazo do Desconto (dias antes do vencimento)'),
        ),
        migrations.AddField(
            model_name='installment',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('NONE', 'Sem desconto'), ('FIXED', 'Valor fixo (R$)'), ('PERCENTAGE', 'Percentual (%)')], default='NONE', max_length=15, verbose_name='Tipo de Desconto'),
        ),
        migrations.AddField(
            model_name='installment',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Valor do Desconto'),
        ),
        migrations.AddField(
            model_name='installment',
            name='fine_type',
            field=models.CharField(blank=True, choices=[('NONE', 'Sem multa'), ('FIXED', 'Valor fixo (R$)'), ('PERCENTAGE', 'Percentual (%)')], default='NONE', max_length=15, verbose_name='Tipo de Multa'),
        ),
        migrations.AddField(
            model_name='installment',
            name='fine_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Valor da Multa'),
        ),
        migrations.AddField(
            model_name='installment',
            name='interest_monthly',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Juros por Atraso (% a.m.)'),
        ),
    ]
