# Generated by Django 5.2.12 on 2026-08-08 03:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0113_remove_billing_discount_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número da Nota')),
                ('series', models.CharField(blank=True, max_length=10, verbose_name='Série')),
                ('access_key', models.CharField(blank=True, max_length=44, verbose_name='Chave de Acesso (NF-e)')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('LANCADA', 'Lançada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=10, verbose_name='Status')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='purchase_invoices/xml/', verbose_name='XML da NF-e')),
                ('generate_expense', models.BooleanField(default=False, verbose_name='Gerar Conta a Pagar')),
                ('expense_due_date', models.DateField(blank=True, null=True, verbose_name='Vencimento da Conta a Pagar')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('launched_at', models.DateTimeField(blank=True, null=True, verbose_name='Lançada em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoice', to='services.expense', verbose_name='Conta a Pagar Gerada')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='services.supplier', verbose_name='Fornecedor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lançada por')),
            ],
            options={
                'verbose_name': 'Nota de Entrada',
                'verbose_name_plural': 'Notas de Entrada',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo Unitário')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.purchaseinvoice', verbose_name='Nota de Entrada')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_items', to='services.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item da Nota de Entrada',
                'verbose_name_plural': 'Itens da Nota de Entrada',
            },
        ),
    ]
