# Generated by Django 5.2.12 on 2026-08-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0114_purchaseinvoice_purchaseinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistory',
            name='operation_type',
            field=models.CharField(choices=[('CATALOG', 'Gestão de Catálogo'), ('STOCK', 'Atualização de Estoque'), ('BLING', 'Importação Bling')], default='CATALOG', max_length=10, verbose_name='Tipo de Operação'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='preview_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados da Prévia'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('BLOQUEADA', 'Bloqueada'), ('PRONTA', 'Pronta para confirmar'), ('CONCLUIDA', 'Concluída'), ('FALHA', 'Falha')], default='CONCLUIDA', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='bling_code',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Código no Bling'),
        ),
        migrations.AddField(
            model_name='product',
            name='bling_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='ID no Bling'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados Externos'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Peso Líquido (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Código no Fornecedor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Estoque Atual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Estoque Máximo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Estoque Mínimo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('UNIDADE', 'Unidade (un)'), ('METRO', 'Metro (mt)'), ('M2', 'Metro Quadrado (m²)'), ('LITRO', 'Litro (lt)'), ('QUILO', 'Quilo (kg)'), ('PC', 'Peça (pc)'), ('CX', 'Caixa (cx)'), ('CE', 'Cento (ce)'), ('CT', 'Cartela (ct)'), ('PR', 'Par (pr)'), ('PCT', 'Pacote (pct)'), ('PT', 'Pote (pt)'), ('RL', 'Rolo (rl)'), ('MO', 'Mão de obra (mo)'), ('BR', 'Barra (br)'), ('JO', 'Jogo (jo)'), ('HR', 'Hora (hr)'), ('TB', 'Tubo (tb)'), ('SC', 'Saco (sc)')], default='UNIDADE', max_length=10, verbose_name='Unidade de Venda'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='saldo_apos',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Saldo Após'),
        ),
    ]
