# Generated by Django 5.2.12 on 2026-09-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0118_alter_importhistory_operation_type_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('PRESENCIAL', 'Venda presencial'), ('DISTANCIA', 'Venda à distância')], default='PRESENCIAL', max_length=20, verbose_name='Tipo de Venda'),
        ),
    ]
