# Generated by Django 5.2.12 on 2026-09-18 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_receivable_methods(apps, schema_editor):
    PaymentMethod = apps.get_model('services', 'PaymentMethod')
    PaymentMethod.objects.filter(tipo_provedor__in=['BOLETO', 'CREDIARIO']).update(pos_behavior='RECEIVABLE')


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0119_sale_sale_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('closing_mode', models.CharField(choices=[('BLIND', 'Fechamento cego'), ('ASSISTED', 'Fechamento assistido')], default='ASSISTED', max_length=10, verbose_name='Modo de fechamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['name'],
                'permissions': [('operate_pos', 'Pode operar o frente de caixa'), ('manage_pos_registers', 'Pode gerenciar caixas'), ('view_pos_reports', 'Pode visualizar relatórios do caixa'), ('approve_pos_closing', 'Pode aprovar e reabrir fechamentos')],
            },
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='pos_behavior',
            field=models.CharField(choices=[('RECEIVED_NOW', 'Recebido no ato'), ('RECEIVABLE', 'Conta a receber'), ('DISABLED', 'Não disponível no PDV')], default='RECEIVED_NOW', max_length=20, verbose_name='Comportamento no PDV'),
        ),
        migrations.RunPython(set_receivable_methods, migrations.RunPython.noop),
        migrations.AddField(
            model_name='sale',
            name='origin',
            field=models.CharField(choices=[('ADMIN', 'Administrativo'), ('POS', 'Frente de Caixa')], db_index=True, default='ADMIN', max_length=10, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='amount_tendered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Recebido'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Troco'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_payments', to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='services.client', verbose_name='Cliente'),
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('PENDING_APPROVAL', 'Aguardando aprovação'), ('CLOSED', 'Fechado')], db_index=True, default='OPEN', max_length=20)),
                ('opening_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fundo inicial')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('closing_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='services.cashregister', verbose_name='Caixa')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('OPENING', 'Abertura'), ('SALE', 'Venda'), ('SUPPLY', 'Suprimento'), ('WITHDRAWAL', 'Sangria'), ('REFUND', 'Devolução'), ('ADJUSTMENT', 'Ajuste')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor líquido')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.paymentmethod')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='services.sale')),
                ('sale_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='services.salereturn')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='services.cashsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashClosingCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('declared_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.paymentmethod')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_counts', to='services.cashsession')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='services.cashsession', verbose_name='Sessão de Caixa'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='services.cashsession', verbose_name='Sessão de Caixa'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('register', 'operator'), name='unique_open_register_operator'),
        ),
        migrations.AddConstraint(
            model_name='cashclosingcount',
            constraint=models.UniqueConstraint(fields=('session', 'payment_method'), name='unique_closing_method'),
        ),
    ]
