# Generated by Django 5.2.12 on 2026-09-28 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0017_gatewaycharge_payment_method_poschargeattempt'),
        ('services', '0121_salesettings_repeated_item_behavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='pos_payment_behavior',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='public_billing_enabled',
            field=models.BooleanField(default=False, verbose_name='Disponível no link público de cobrança'),
        ),
        migrations.AddField(
            model_name='sale',
            name='pos_checkout_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='gateway_charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='pagamentos.gatewaycharge'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='pos_behavior',
            field=models.CharField(choices=[('RECEIVED_NOW', 'Recebido no ato'), ('RECEIVABLE', 'Conta a receber'), ('DISABLED', 'Não disponível no PDV'), ('WAIT_GATEWAY', 'Aguardar confirmação do gateway')], default='RECEIVED_NOW', max_length=20, verbose_name='Comportamento no PDV'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado'), ('EM_ANDAMENTO', 'Em Andamento'), ('PRONTO', 'Pronto'), ('RECEBIDO', 'Recebido'), ('VENDA_AGENCIADA', 'Venda Agenciada'), ('RASCUNHO', 'Rascunho'), ('FINALIZADA', 'Finalizada'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento')], default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
    ]
