# Generated by Django 5.2.12 on 2026-09-29 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0123_payment_channel_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='uses_default_pos_client',
            field=models.BooleanField(default=False, verbose_name='Consumidor padrão do PDV'),
        ),
        migrations.AddField(
            model_name='salesettings',
            name='pos_default_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.client', verbose_name='Consumidor padrão do PDV'),
        ),
    ]
