# Generated by Django 5.2.12 on 2026-09-29 23:48

from django.db import migrations, models


def initialize_existing(apps, schema_editor):
    PaymentMethod = apps.get_model('services', 'PaymentMethod')
    PaymentMethod.objects.filter(integra_gateway=True, tipo_provedor='PIX').update(integrated_product='ASAAS_PIX')
    PaymentMethod.objects.filter(integra_gateway=True, tipo_provedor='BOLETO').update(integrated_product='ASAAS_BOLETO')


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0124_pos_default_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='integrated_product',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Produto integrado'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='tarifa_maxima',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Zero significa sem limite.', max_digits=10, verbose_name='Tarifa Máxima (R$)'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='fee_status',
            field=models.CharField(choices=[('UNKNOWN', 'Não verificado'), ('ESTIMATED', 'Estimado'), ('CONFIRMED', 'Confirmado')], default='UNKNOWN', max_length=12, verbose_name='Situação da tarifa'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='fee_terms',
            field=models.JSONField(blank=True, default=dict, verbose_name='Regra de tarifa aplicada'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='gateway_split_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID do split conciliado'),
        ),
        migrations.RunPython(initialize_existing, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='salepayment', name='fee_status',
            field=models.CharField(choices=[('UNKNOWN', 'Não verificado'), ('ESTIMATED', 'Estimado'), ('CONFIRMED', 'Confirmado')], default='CONFIRMED', max_length=12, verbose_name='Situação da tarifa'),
        ),
    ]
