# Generated by Django 5.2.12 on 2026-10-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0125_paymentmethod_integrated_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesettings',
            name='default_sale_type',
            field=models.CharField(choices=[('PRESENCIAL', 'Venda presencial'), ('DISTANCIA', 'Venda à distância')], default='PRESENCIAL', max_length=20, verbose_name='Tipo padrão de venda'),
        ),
    ]
