# Generated by Django 5.2.12 on 2026-10-04 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0017_gatewaycharge_payment_method_poschargeattempt'),
        ('services', '0126_salesettings_default_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesettings',
            name='default_charge_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pagamentos.billingchargeconfig', verbose_name='Regra de cobrança padrão para vendas'),
        ),
        migrations.AddField(
            model_name='salesettings',
            name='default_sale_status',
            field=models.CharField(choices=[('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado'), ('EM_ANDAMENTO', 'Em Andamento'), ('PRONTO', 'Pronto'), ('RECEBIDO', 'Recebido'), ('VENDA_AGENCIADA', 'Venda Agenciada'), ('RASCUNHO', 'Rascunho'), ('FINALIZADA', 'Finalizada'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento')], default='RASCUNHO', max_length=20, verbose_name='Status padrão da venda'),
        ),
    ]
