# Generated by Django 5.2.12 on 2026-07-17 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0109_service_codigo_tributacao_nacional_iss'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox (Homologação)'), ('PRODUCTION', 'Produção')], default='SANDBOX', max_length=15, verbose_name='Ambiente')),
                ('status', models.CharField(choices=[('NAO_CONFIGURADO', 'Não configurado'), ('PENDENTE_CERTIFICADO', 'Empresa criada — certificado pendente'), ('ATIVO', 'Ativo'), ('ERRO', 'Erro')], default='NAO_CONFIGURADO', max_length=25, verbose_name='Status')),
                ('status_detail', models.TextField(blank=True, verbose_name='Detalhe do Status')),
                ('focus_empresa_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID da Empresa na Focus')),
                ('token_producao', models.CharField(blank=True, help_text='Token da empresa na Focus (ambiente de produção). Copie do painel da Focus ("Serviços > Minhas Empresas") ou gere automaticamente usando o botão de cadastro de empresa abaixo.', max_length=255, verbose_name='Token de Produção')),
                ('token_homologacao', models.CharField(blank=True, max_length=255, verbose_name='Token de Homologação')),
                ('account_token', models.CharField(blank=True, help_text='Necessário apenas para cadastrar a empresa por aqui via API (botão "Cadastrar empresa na Focus"). Não é o mesmo token da empresa — é o token de conta, disponível no painel da Focus. Se preferir, cadastre a empresa direto no painel da Focus e cole os tokens de produção/homologação acima manualmente.', max_length=255, verbose_name='Token de Conta/Revenda da Focus')),
                ('razao_social', models.CharField(blank=True, max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Municipal')),
                ('regime_tributario', models.IntegerField(choices=[(1, '1 - Simples Nacional'), (2, '2 - Simples Nacional - excesso de sublimite de receita bruta'), (3, '3 - Regime Normal'), (4, '4 - MEI')], default=1, verbose_name='Regime Tributário (CRT)')),
                ('logradouro', models.CharField(blank=True, max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('municipio', models.CharField(blank=True, default='Goiânia', max_length=100, verbose_name='Município')),
                ('codigo_municipio_ibge', models.CharField(blank=True, default='5208707', help_text='Código IBGE de 7 dígitos do município do prestador/emitente. Padrão: Goiânia/GO.', max_length=7, verbose_name='Código IBGE do Município')),
                ('uf', models.CharField(blank=True, default='GO', max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('habilita_nfe', models.BooleanField(default=False, verbose_name='Habilita NFe')),
                ('habilita_nfce', models.BooleanField(default=False, verbose_name='Habilita NFCe')),
                ('habilita_nfse', models.BooleanField(default=True, verbose_name='Habilita NFSe Nacional')),
                ('certificado_valido_ate', models.DateTimeField(blank=True, null=True, verbose_name='Certificado Válido Até')),
                ('certificado_enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Certificado Enviado em')),
                ('webhook_token', models.CharField(blank=True, max_length=100, verbose_name='Token do Webhook')),
                ('default_codigo_tributacao_iss', models.CharField(blank=True, help_text='Usado quando o serviço faturado não tiver um código de tributação nacional do ISS próprio.', max_length=6, verbose_name='Código de Tributação Nacional do ISS (padrão)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Nota Fiscal',
                'verbose_name_plural': 'Configuração de Nota Fiscal',
            },
        ),
        migrations.CreateModel(
            name='NFeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NFE', 'NFe'), ('NFCE', 'NFCe'), ('NFSE', 'NFSe Nacional')], max_length=10, verbose_name='Tipo de Documento')),
                ('ref', models.CharField(max_length=80, unique=True, verbose_name='Referência (nosso ID enviado à Focus)')),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando Autorização'), ('AUTORIZADO', 'Autorizado'), ('ERRO', 'Erro na Autorização'), ('CANCELADO', 'Cancelado')], default='PROCESSANDO', max_length=15, verbose_name='Status')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('serie', models.CharField(blank=True, max_length=10, verbose_name='Série')),
                ('chave_acesso', models.CharField(blank=True, max_length=60, verbose_name='Chave de Acesso')),
                ('codigo_verificacao', models.CharField(blank=True, max_length=60, verbose_name='Código de Verificação (NFSe)')),
                ('status_sefaz', models.CharField(blank=True, max_length=10, verbose_name='Status SEFAZ/Prefeitura')),
                ('mensagem_sefaz', models.TextField(blank=True, verbose_name='Mensagem SEFAZ/Prefeitura')),
                ('xml_url', models.URLField(blank=True, max_length=500, verbose_name='URL do XML')),
                ('pdf_url', models.URLField(blank=True, max_length=500, verbose_name='URL do PDF (DANFE/DANFCe/DANFSe)')),
                ('qrcode_url', models.URLField(blank=True, max_length=500, verbose_name='URL do QR Code (NFCe)')),
                ('error_details', models.JSONField(blank=True, null=True, verbose_name='Detalhes do Erro')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Última Resposta Bruta da Focus')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('cancel_justificativa', models.TextField(blank=True, verbose_name='Justificativa do Cancelamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_documents', to='services.sale', verbose_name='Venda')),
                ('service_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_documents', to='services.serviceorder', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Documento Fiscal',
                'verbose_name_plural': 'Documentos Fiscais',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('sale__isnull', False), ('service_order__isnull', True)), models.Q(('sale__isnull', True), ('service_order__isnull', False)), _connector='OR'), name='fiscal_nfedocument_exactly_one_owner')],
            },
        ),
    ]
