# Generated by Django 5.2.12 on 2026-07-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfeconfig',
            name='default_ibs_cbs_classificacao_tributaria',
            field=models.CharField(blank=True, help_text='Código de Classificação Tributária do IBS/CBS (Reforma Tributária). Consulte seu contador.', max_length=6, verbose_name='Classificação Tributária IBS/CBS (padrão)'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='default_ibs_cbs_situacao_tributaria',
            field=models.CharField(blank=True, help_text='Código de Situação Tributária do IBS/CBS (Reforma Tributária). Consulte seu contador.', max_length=3, verbose_name='CST IBS/CBS (padrão)'),
        ),
    ]
