# Generated by Django 5.2.12 on 2026-07-18 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_nfeconfig_default_ibs_cbs_classificacao_tributaria_and_more'),
        ('services', '0109_service_codigo_tributacao_nacional_iss'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nfedocument',
            name='fiscal_nfedocument_exactly_one_owner',
        ),
        migrations.RemoveField(
            model_name='nfedocument',
            name='service_order',
        ),
        migrations.AddField(
            model_name='nfedocument',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_documents', to='services.serviceordertask', verbose_name='Etapa da OS'),
        ),
        migrations.AddConstraint(
            model_name='nfedocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sale__isnull', False), ('task__isnull', True)), models.Q(('sale__isnull', True), ('task__isnull', False)), _connector='OR'), name='fiscal_nfedocument_exactly_one_owner'),
        ),
    ]
