# Generated by Django 5.2.12 on 2026-07-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_remove_nfedocument_fiscal_nfedocument_exactly_one_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfeconfig',
            name='default_codigo_tributacao_municipal_iss',
            field=models.CharField(blank=True, help_text='Tabela própria da prefeitura (distinto do código nacional acima). Usado quando o serviço faturado não tiver um código municipal próprio.', max_length=3, verbose_name='Código de Tributação Municipal do ISS (padrão)'),
        ),
    ]
