# Generated by Django 5.2.12 on 2026-07-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_nfeconfig_default_codigo_tributacao_municipal_iss'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfeconfig',
            name='default_codigo_indicador_operacao',
            field=models.CharField(blank=True, help_text='Indicador de operação da Reforma Tributária (Anexo VIII — correlação item LC 116 x NBS x cIndOp x cClassTrib). Usado quando o serviço faturado não tiver um código próprio.', max_length=6, verbose_name='Código Indicador de Operação — cIndOp (padrão)'),
        ),
    ]
