# Generated by Django 5.2.12 on 2026-07-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0005_nfeconfig_default_codigo_indicador_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfeconfig',
            name='default_codigo_nbs',
            field=models.CharField(blank=True, help_text='Nomenclatura Brasileira de Serviços, 9 dígitos sem pontos (Anexo VIII). Diferente do cIndOp, o NBS não é único por item LC 116 — varia por tipo específico de serviço, então esse default só é confiável se todos os serviços faturados forem do mesmo tipo. Usado quando o serviço faturado não tiver um código NBS próprio.', max_length=9, verbose_name='Código NBS (padrão)'),
        ),
    ]
