# Generated by Django 5.2.12 on 2026-07-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_nfeconfig_default_codigo_nbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_cofins_aliquota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota COFINS % — Asaas (padrão)'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_csll_aliquota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota CSLL % — Asaas (padrão)'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_inss_aliquota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota INSS % — Asaas (padrão)'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_ir_aliquota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota IR % — Asaas (padrão)'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_iss_aliquota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota ISS % — Asaas (padrão)'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_municipal_service_code',
            field=models.CharField(blank=True, help_text='municipalServiceCode — código do serviço na tabela da prefeitura, conforme cadastrado no Asaas. Opcional; use municipalServiceId no Asaas se preferir referenciar por ID.', max_length=20, verbose_name='Código do Serviço Municipal — Asaas (padrão)'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_municipal_service_name',
            field=models.CharField(blank=True, help_text='municipalServiceName da nota — texto livre igual ao cadastrado na tabela de serviços municipais do Asaas ("Listar serviços municipais").', max_length=255, verbose_name='Nome do Serviço Municipal — Asaas (padrão)'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_pis_aliquota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota PIS % — Asaas (padrão)'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_retain_iss',
            field=models.BooleanField(default=False, help_text='retainIss — se o ISS é retido pelo tomador do serviço.', verbose_name='Reter ISS — Asaas (padrão)'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='nfse_provider',
            field=models.CharField(choices=[('FOCUS', 'Focus NFe'), ('ASAAS', 'Asaas')], default='FOCUS', help_text='Qual gateway emite NFSe. NFe/NFCe de produto continuam sempre pela Focus — o Asaas só emite nota de serviço.', max_length=10, verbose_name='Provedor de NFSe'),
        ),
    ]
