# Generated by Django 5.2.12 on 2026-07-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0007_nfeconfig_asaas_cofins_aliquota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfedocument',
            name='gateway_id',
            field=models.CharField(blank=True, help_text='ID atribuído pelo gateway (ex: id da invoice no Asaas). A Focus é consultada pelo nosso `ref`; o Asaas exige o próprio ID nos endpoints de consulta/cancelamento.', max_length=80, verbose_name='ID no Gateway'),
        ),
        migrations.AlterField(
            model_name='nfedocument',
            name='ref',
            field=models.CharField(max_length=80, unique=True, verbose_name='Referência (nosso ID enviado ao gateway)'),
        ),
    ]
