# Generated by Django 5.2.12 on 2026-07-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0008_nfedocument_gateway_id_alter_nfedocument_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_municipal_service_id',
            field=models.CharField(blank=True, help_text='municipalServiceId — id do catálogo de serviços da Asaas (GET /v3/fiscalInfo/services). Forma recomendada pela Asaas: referencia exatamente o serviço já homologado, sem risco de nome/código digitado não bater com o cadastro deles. Escolhido pela busca na tela de configuração; os campos de nome/código abaixo são só um fallback manual.', max_length=20, verbose_name='ID do Serviço Municipal — Asaas (padrão)'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_municipal_service_label',
            field=models.CharField(blank=True, help_text='Cache só para exibição — texto do serviço escolhido via busca (evita nova chamada à Asaas só para mostrar o que já foi selecionado).', max_length=255, verbose_name='Descrição do Serviço Selecionado — Asaas'),
        ),
        migrations.AlterField(
            model_name='nfeconfig',
            name='asaas_municipal_service_code',
            field=models.CharField(blank=True, help_text='municipalServiceCode — só é usado se "ID do Serviço Municipal" acima estiver vazio.', max_length=20, verbose_name='Código do Serviço Municipal — Asaas (padrão, fallback manual)'),
        ),
        migrations.AlterField(
            model_name='nfeconfig',
            name='asaas_municipal_service_name',
            field=models.CharField(blank=True, help_text='municipalServiceName da nota — texto livre igual ao cadastrado na tabela de serviços municipais do Asaas. Só é usado se "ID do Serviço Municipal" acima estiver vazio.', max_length=255, verbose_name='Nome do Serviço Municipal — Asaas (padrão, fallback manual)'),
        ),
    ]
