# Generated by Django 5.2.12 on 2026-07-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0009_nfeconfig_asaas_municipal_service_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfeconfig',
            name='default_codigo_nbs',
            field=models.CharField(blank=True, help_text='Nomenclatura Brasileira de Serviços (Anexo VIII). Para o Asaas, use o formato com pontos igual ao devolvido pelo catálogo dele (GET /v3/fiscalInfo/nbsCodes), ex: "1.0105.30.00" — não confirmamos se a Asaas aceita o formato sem pontos no payload da nota. Diferente do cIndOp, o NBS não é único por item LC 116 — varia por tipo específico de serviço, então esse default só é confiável se todos os serviços faturados forem do mesmo tipo.', max_length=15, verbose_name='Código NBS (padrão)'),
        ),
    ]
