# Generated by Django 5.2.12 on 2026-07-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0010_alter_nfeconfig_default_codigo_nbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_cnae',
            field=models.CharField(blank=True, help_text='Só números, sem pontuação (ex: 4399199).', max_length=10, verbose_name='Código CNAE — Asaas'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_cultural_projects_promoter',
            field=models.BooleanField(default=False, verbose_name='Incentivador Cultural — Asaas'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_fiscal_email',
            field=models.EmailField(blank=True, help_text='fiscalInfo.email — usado pela Asaas para notificações de nota fiscal (pode ser diferente do e-mail da própria conta Asaas).', max_length=254, verbose_name='E-mail Fiscal — Asaas'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_lote_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número do Lote — Asaas'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_national_portal_tax_calc_regime',
            field=models.CharField(blank=True, choices=[('0', 'Nenhum'), ('1', 'Tributos federais e municipal pelo SN'), ('2', 'Tributos federais pelo SN e ISSQN fora do SN'), ('3', 'Tributos federais e municipal fora do SN')], default='', help_text='Preencher só se sua empresa for ME/EPP optante do Simples Nacional.', max_length=1, verbose_name='Regime de Apuração Tributária SN — Asaas'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_rps_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número do RPS — Asaas'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_rps_serie',
            field=models.CharField(blank=True, max_length=10, verbose_name='Série do RPS — Asaas'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_service_list_item',
            field=models.CharField(blank=True, help_text='Formato com ponto, mantendo a formatação da LC 116 (ex: 07.05, não 0705).', max_length=10, verbose_name='Item da Lista de Serviços — Asaas'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_simples_nacional',
            field=models.BooleanField(default=True, verbose_name='Optante pelo Simples Nacional — Asaas'),
        ),
        migrations.AddField(
            model_name='nfeconfig',
            name='asaas_special_tax_regime',
            field=models.CharField(blank=True, choices=[('0', ' - '), ('1', 'Microempresa Municipal'), ('2', 'Estimativa'), ('3', 'Sociedade de Profissionais'), ('4', 'Cooperativa'), ('5', 'MEI - Simples Nacional'), ('6', 'ME EPP - Simples Nacional')], default='0', max_length=1, verbose_name='Regime Especial de Tributação — Asaas'),
        ),
    ]
