# Generated by Django 5.2.12 on 2026-07-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0011_nfeconfig_asaas_cnae_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfeconfig',
            name='base_erp_webhook_token',
            field=models.CharField(blank=True, help_text='Cole aqui o mesmo token configurado no webhook do Base ERP (painel deles). Usado para validar o header "asaas-access-token" recebido em /integracoes/fiscal/webhook/base_erp/.', max_length=100, verbose_name='Token do Webhook — Base ERP'),
        ),
        migrations.AlterField(
            model_name='nfeconfig',
            name='nfse_provider',
            field=models.CharField(choices=[('FOCUS', 'Focus NFe'), ('ASAAS', 'Asaas')], default='FOCUS', help_text='Qual gateway emite NFSe. NFe/NFCe de produto são emitidas pelo Base ERP (ver fiscal/gateways/base_erp.py) — o Asaas só emite nota de serviço.', max_length=10, verbose_name='Provedor de NFSe'),
        ),
    ]
