# Generated by Django 5.2.12 on 2026-04-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='Provedor')),
                ('payload', models.JSONField(verbose_name='Payload Bruto')),
                ('headers', models.JSONField(blank=True, null=True, verbose_name='Cabeçalhos')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processed', 'Processado'), ('failed', 'Falha')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas/Erros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Evento de Webhook',
                'verbose_name_plural': 'Eventos de Webhook',
                'ordering': ['-created_at'],
            },
        ),
    ]
