# Generated by Django 5.2.12 on 2026-05-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Minha Empresa', max_length=255, verbose_name='Razão Social / Nome Fantasia')),
                ('company_cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('company_address', models.TextField(blank=True, help_text='Endereço que sairá no cabeçalho do PDF do Orçamento', null=True, verbose_name='Endereço Completo')),
                ('company_website', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo da Empresa')),
                ('chatwoot_base_url', models.URLField(default='https://app.chatwoot.com', help_text='URL base da sua instância do Chatwoot (se self-hosted, altere)', verbose_name='Chatwoot API URL')),
                ('chatwoot_account_id', models.CharField(blank=True, help_text='ID da conta no Chatwoot', max_length=50, null=True, verbose_name='Account ID')),
                ('chatwoot_inbox_id', models.CharField(blank=True, help_text='ID da caixa de entrada do WhatsApp', max_length=50, null=True, verbose_name='Inbox ID (WhatsApp)')),
                ('chatwoot_api_token', models.CharField(blank=True, help_text='Token de acesso à API (do usuário/bot)', max_length=255, null=True, verbose_name='User API Access Token')),
                ('chatwoot_budget_template', models.CharField(blank=True, help_text='Ex: enviar_orcamento_v1', max_length=100, null=True, verbose_name='Nome do Template de Orçamento')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
