# Generated by Django 5.2.12 on 2026-05-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0002_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='meta_access_token',
            field=models.CharField(blank=True, help_text='Token de acesso permanente do Gerenciador de Negócios da Meta', max_length=512, null=True, verbose_name='Meta System User Access Token'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='meta_waba_id',
            field=models.CharField(blank=True, help_text='Necessário para buscar definições de templates diretamente na Meta', max_length=100, null=True, verbose_name='WhatsApp Business Account ID'),
        ),
    ]
