# Generated by Django 5.2.12 on 2026-05-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0003_systemconfig_meta_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='chatwoot_pix_label',
            field=models.CharField(default='pix-enviado', help_text='Etiqueta que será aplicada na conversa ao enviar o PIX', max_length=50, verbose_name='Etiqueta para PIX Enviado'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='chatwoot_pix_template',
            field=models.CharField(blank=True, help_text='Ex: enviar_pix_v1', max_length=100, null=True, verbose_name='Nome do Template de Cobrança/PIX'),
        ),
    ]
