# Generated by Django 5.2.12 on 2026-05-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0004_systemconfig_chatwoot_pix_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='pix_bank',
            field=models.CharField(default='Bradesco', max_length=100, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='pix_key',
            field=models.CharField(default='41426314000138', max_length=100, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='pix_recipient',
            field=models.CharField(default='Dourados Calhas', max_length=255, verbose_name='Destinatário (Nome/Razão Social)'),
        ),
    ]
