# Generated by Django 5.2.12 on 2026-05-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0006_systemconfig_chatwoot_evaluation_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='meta_phone_number_id',
            field=models.CharField(blank=True, help_text='ID do número de telefone na API da Meta', max_length=100, null=True, verbose_name='WhatsApp Phone Number ID'),
        ),
    ]
