# Generated by Django 5.2.12 on 2026-05-29 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0007_systemconfig_meta_phone_number_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Regra/Descrição')),
                ('model_name', models.CharField(choices=[('ServiceOrder', 'Ordem de Serviço'), ('ServiceOrderTask', 'Etapa de Serviço'), ('Sale', 'Venda')], max_length=50, verbose_name='Modelo')),
                ('event_type', models.CharField(choices=[('CREATE', 'Criação do Registro'), ('STATUS_CHANGE', 'Alteração de Status')], max_length=20, verbose_name='Evento Gatilho')),
                ('from_status', models.CharField(blank=True, help_text='Deixe em branco para disparar vindo de qualquer status', max_length=50, null=True, verbose_name='Status de Origem')),
                ('to_status', models.CharField(blank=True, help_text='O status que o registro deve assumir para disparar a regra', max_length=50, null=True, verbose_name='Status de Destino')),
                ('template_name', models.CharField(help_text='Ex: boas_vindas_cliente', max_length=100, verbose_name='Nome do Template na Meta')),
                ('phone_field_path', models.CharField(default='client', help_text='Caminho para chegar no objeto Cliente. Ex: client_property.client para OS, ou client para Venda.', max_length=255, verbose_name='Caminho para o Cliente/Telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Notificação',
                'verbose_name_plural': 'Configurações de Notificações',
                'ordering': ['model_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='Índice da Variável (Ex: 1 para {{1}})')),
                ('field_path', models.CharField(help_text='Ex: number, client_property.client.name, total_value', max_length=255, verbose_name='Caminho do Campo no Modelo')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='integracoes.notificationconfig', verbose_name='Configuração')),
            ],
            options={
                'verbose_name': 'Variável de Notificação',
                'verbose_name_plural': 'Variáveis de Notificação',
                'ordering': ['index'],
                'unique_together': {('config', 'index')},
            },
        ),
    ]
