# Generated by Django 5.2.12 on 2026-05-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0008_notificationconfig_notificationvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='tax_regime',
            field=models.CharField(choices=[('SIMPLES', 'Simples Nacional'), ('NORMAL', 'Regime Normal')], default='SIMPLES', max_length=20, verbose_name='Regime Tributário'),
        ),
    ]
