# Generated by Django 5.2.12 on 2026-05-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0009_systemconfig_tax_regime'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='state',
            field=models.CharField(default='MS', help_text='UF da empresa para cálculo de CFOP', max_length=2, verbose_name='UF'),
        ),
    ]
