# Generated by Django 5.2.12 on 2026-05-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0010_systemconfig_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='billing_default_due_days',
            field=models.PositiveIntegerField(default=1, help_text='Prazo padrão em dias para o primeiro vencimento após a conclusão do serviço/venda.', verbose_name='Dias Padrão para Vencimento'),
        ),
    ]
