# Generated by Django 5.2.12 on 2026-06-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0011_systemconfig_billing_default_due_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationconfig',
            name='event_type',
            field=models.CharField(choices=[('CRIAR', 'Criação do Registro'), ('MUDANCA_STATUS', 'Alteração de Status')], max_length=20, verbose_name='Evento Gatilho'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processado', 'Processado'), ('falha', 'Falha')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
