# Generated by Django 5.2.12 on 2026-06-01 12:56

from django.db import migrations

def translate_webhook_data(apps, schema_editor):
    mapping = {
        'pending': 'pendente',
        'processed': 'processado',
        'failed': 'falha',
    }
    
    WebhookEvent = apps.get_model('integracoes', 'WebhookEvent')
    for old, new in mapping.items():
        WebhookEvent.objects.filter(status=old).update(status=new)

class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0012_alter_notificationconfig_event_type_and_more'),
    ]

    operations = [
        migrations.RunPython(translate_webhook_data),
    ]
