# Generated by Django 5.2.12 on 2026-06-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0013_traduzir_webhooks_dados'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationconfig',
            name='fixed_phone',
            field=models.CharField(blank=True, help_text='Somente se o tipo for Número Fixo. Ex: 5567999999999', max_length=20, null=True, verbose_name='Telefone Fixo'),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='recipient_type',
            field=models.CharField(choices=[('DYNAMIC', 'Campo Dinâmico (Variável do Modelo)'), ('FIXED', 'Número Fixo (Sempre o mesmo)')], default='DYNAMIC', max_length=20, verbose_name='Tipo de Destinatário'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='phone_field_path',
            field=models.CharField(blank=True, default='client_property.client', help_text='Caminho para chegar no objeto Cliente ou campo de Telefone. Ex: client_property.client para OS.', max_length=255, null=True, verbose_name='Caminho para o Cliente/Telefone'),
        ),
    ]
