# Generated by Django 5.2.12 on 2026-06-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0014_notificationconfig_fixed_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationconfig',
            name='header_media_type',
            field=models.CharField(choices=[('NONE', 'Nenhum'), ('BUDGET_PDF', 'Orçamento (PDF Gerado)'), ('REPORT_PDF', 'Relatório de Execução (PDF Gerado)'), ('STATIC_PDF', 'PDF Estático (Upload)')], default='NONE', max_length=20, verbose_name='Tipo de Mídia no Cabeçalho'),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='static_media_file',
            field=models.FileField(blank=True, help_text='Somente se o tipo for PDF Estático', null=True, upload_to='notifications/static/', verbose_name='Arquivo Estático'),
        ),
    ]
