# Generated by Django 5.2.12 on 2026-06-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0015_notificationconfig_header_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationconfig',
            name='from_status',
            field=models.CharField(blank=True, help_text='Opcional: Disparar apenas se vier deste status. Deixe vazio para qualquer origem.', max_length=50, null=True, verbose_name='Status de Origem (Filtro)'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='to_status',
            field=models.CharField(blank=True, help_text='Obrigatório: O status que o registro deve assumir para disparar a regra.', max_length=50, null=True, verbose_name='Status de Destino (Gatilho)'),
        ),
    ]
