# Generated by Django 5.2.12 on 2026-06-04 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0016_alter_notificationconfig_from_status_and_more'),
        ('services', '0084_add_sale_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Etapa')),
                ('template_name', models.CharField(max_length=200, verbose_name='Template WhatsApp (Meta)')),
                ('trigger_type', models.CharField(choices=[('BEFORE_DUE', 'Antes do Vencimento'), ('ON_DUE', 'No Dia do Vencimento'), ('AFTER_DUE', 'Após o Vencimento')], default='AFTER_DUE', max_length=20, verbose_name='Tipo de Gatilho')),
                ('days_offset', models.PositiveIntegerField(default=0, help_text='Número de dias antes ou após o vencimento para disparar esta etapa', verbose_name='Dias')),
                ('stop_after_days_overdue', models.PositiveIntegerField(default=60, help_text='Não envia mensagem se a parcela estiver em atraso há mais dias que este valor', verbose_name='Parar após (dias em atraso)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Régua de Cobrança',
                'verbose_name_plural': 'Réguas de Cobrança',
                'ordering': ['trigger_type', 'days_offset'],
            },
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='event_type',
            field=models.CharField(choices=[('CRIAR', 'Criação do Registro'), ('MUDANCA_STATUS', 'Alteração de Status'), ('PAGAMENTO_PARCIAL', 'Pagamento Parcial Registrado'), ('PAGAMENTO_INTEGRAL', 'Pagamento Integral Registrado')], max_length=20, verbose_name='Evento Gatilho'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='model_name',
            field=models.CharField(choices=[('ServiceOrder', 'Ordem de Serviço'), ('ServiceOrderTask', 'Etapa de Serviço'), ('Sale', 'Venda'), ('Billing', 'Cobrança (Fatura)'), ('Installment', 'Parcela de Cobrança'), ('ExpenseInstallment', 'Parcela de Despesa (C. a Pagar)')], max_length=50, verbose_name='Modelo'),
        ),
        migrations.CreateModel(
            name='CollectionRuleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('SENT', 'Enviado'), ('FAILED', 'Falhou')], default='SENT', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_logs', to='services.installment', verbose_name='Parcela')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integracoes.collectionrule', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Log de Cobrança',
                'verbose_name_plural': 'Logs de Cobrança',
                'ordering': ['-sent_at'],
                'unique_together': {('installment', 'rule')},
            },
        ),
        migrations.CreateModel(
            name='CollectionRuleVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='Índice (Ex: 1 para {{1}})')),
                ('field_path', models.CharField(max_length=255, verbose_name='Caminho do Campo')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='integracoes.collectionrule', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Variável da Régua',
                'verbose_name_plural': 'Variáveis da Régua',
                'ordering': ['index'],
                'unique_together': {('rule', 'index')},
            },
        ),
    ]
