# Generated by Django 5.2.12 on 2026-06-04 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0017_add_collection_rule_models'),
        ('services', '0084_add_sale_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Régua')),
                ('start_after_days_overdue', models.PositiveIntegerField(default=1, help_text='Só começa a cobrar após a parcela estar em atraso por este número de dias', verbose_name='Iniciar após (dias em atraso)')),
                ('stop_after_days_overdue', models.PositiveIntegerField(default=60, help_text='Para de cobrar se a parcela estiver em atraso há mais dias que este valor', verbose_name='Parar após (dias em atraso)')),
                ('max_occurrences', models.PositiveIntegerField(default=3, help_text='Número máximo de mensagens enviadas por parcela', verbose_name='Máximo de cobranças')),
                ('min_interval_days', models.PositiveIntegerField(default=5, help_text='Intervalo mínimo entre cobranças para saúde da conta Meta', verbose_name='Intervalo mínimo (dias)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Régua de Cobrança',
                'verbose_name_plural': 'Réguas de Cobrança',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='collectionrulelog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='collectionrulelog',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='collectionrulelog',
            name='installment',
        ),
        migrations.CreateModel(
            name='CollectionInstallmentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_occurrence', models.PositiveIntegerField(default=0, verbose_name='Ocorrência Atual')),
                ('last_sent_at', models.DateField(blank=True, null=True, verbose_name='Último Envio')),
                ('next_eligible_date', models.DateField(blank=True, null=True, verbose_name='Próximo Envio Elegível')),
                ('is_paused', models.BooleanField(default=False, verbose_name='Pausado')),
                ('installment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection_state', to='services.installment')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='integracoes.collectionsequence')),
            ],
            options={
                'verbose_name': 'Estado de Cobrança da Parcela',
                'verbose_name_plural': 'Estados de Cobrança das Parcelas',
            },
        ),
        migrations.CreateModel(
            name='CollectionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence', models.PositiveIntegerField(help_text='1 = primeira cobrança, 2 = segunda, etc.', verbose_name='Nº da Ocorrência')),
                ('label', models.CharField(blank=True, help_text='Ex: Tom amigável, Tom firme', max_length=200, verbose_name='Tom / Descrição')),
                ('template_name', models.CharField(max_length=200, verbose_name='Template WhatsApp (Meta)')),
                ('wait_days_before_next', models.PositiveIntegerField(default=7, help_text='Dias a aguardar após este envio antes de enviar a próxima etapa', verbose_name='Aguardar antes da próxima (dias)')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='integracoes.collectionsequence')),
            ],
            options={
                'verbose_name': 'Etapa da Régua',
                'verbose_name_plural': 'Etapas da Régua',
                'ordering': ['occurrence'],
                'unique_together': {('sequence', 'occurrence')},
            },
        ),
        migrations.CreateModel(
            name='CollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_number', models.PositiveIntegerField(verbose_name='Nº da Ocorrência')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('SENT', 'Enviado'), ('FAILED', 'Falhou')], default='SENT', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_logs', to='services.installment')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integracoes.collectionstep')),
            ],
            options={
                'verbose_name': 'Log de Cobrança',
                'verbose_name_plural': 'Logs de Cobrança',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionStepVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='Índice (Ex: 1 para {{1}})')),
                ('field_path', models.CharField(max_length=255, verbose_name='Caminho do Campo')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='integracoes.collectionstep')),
            ],
            options={
                'verbose_name': 'Variável da Etapa',
                'verbose_name_plural': 'Variáveis da Etapa',
                'ordering': ['index'],
                'unique_together': {('step', 'index')},
            },
        ),
        migrations.DeleteModel(
            name='CollectionRuleVariable',
        ),
        migrations.DeleteModel(
            name='CollectionRule',
        ),
        migrations.DeleteModel(
            name='CollectionRuleLog',
        ),
    ]
