# Generated by Django 5.2.12 on 2026-06-04 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0018_add_collection_sequence_models'),
        ('services', '0084_add_sale_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('offset_days', models.IntegerField(default=-1, help_text='Negativo = antes do vencimento (ex: -1 = 1 dia antes), 0 = no vencimento, positivo = após (ex: 3 = 3 dias após vencido)', verbose_name='Offset em Dias')),
                ('template_name', models.CharField(max_length=200, verbose_name='Template WhatsApp (Meta)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lembrete Agendado',
                'verbose_name_plural': 'Lembretes Agendados',
                'ordering': ['offset_days', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('SENT', 'Enviado'), ('FAILED', 'Falhou')], default='SENT', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reminder_logs', to='services.installment')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integracoes.scheduledreminder')),
            ],
            options={
                'verbose_name': 'Log de Lembrete',
                'verbose_name_plural': 'Logs de Lembretes',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReminderVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='Índice (Ex: 1 para {{1}})')),
                ('field_path', models.CharField(max_length=255, verbose_name='Caminho do Campo')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='integracoes.scheduledreminder')),
            ],
            options={
                'verbose_name': 'Variável do Lembrete',
                'verbose_name_plural': 'Variáveis do Lembrete',
                'ordering': ['index'],
                'unique_together': {('reminder', 'index')},
            },
        ),
    ]
