# Generated by Django 5.2.12 on 2026-06-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0019_add_scheduled_reminder_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationconfig',
            name='header_media_type',
            field=models.CharField(choices=[('NONE', 'Nenhum'), ('BUDGET_PDF', 'Orçamento (PDF Gerado)'), ('REPORT_PDF', 'Relatório de Execução (PDF Gerado)'), ('SALE_PDF', 'Relatório de Venda (PDF Gerado)'), ('STATIC_PDF', 'PDF Estático (Upload)')], default='NONE', max_length=20, verbose_name='Tipo de Mídia no Cabeçalho'),
        ),
    ]
