# Generated by Django 5.2.12 on 2026-06-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0020_add_sale_pdf_header_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationvariable',
            options={'ordering': ['component', 'index'], 'verbose_name': 'Variável de Notificação', 'verbose_name_plural': 'Variáveis de Notificação'},
        ),
        migrations.AlterUniqueTogether(
            name='notificationvariable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notificationvariable',
            name='component',
            field=models.CharField(choices=[('BODY', 'Corpo'), ('BUTTON', 'Botão')], default='BODY', max_length=10, verbose_name='Componente'),
        ),
        migrations.AlterField(
            model_name='notificationvariable',
            name='index',
            field=models.PositiveIntegerField(verbose_name='Índice (corpo: 1-based; botão: 0-based)'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationvariable',
            unique_together={('config', 'component', 'index')},
        ),
    ]
