# Generated by Django 5.2.12 on 2026-06-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0021_alter_notificationvariable_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionstepvariable',
            options={'ordering': ['component', 'index'], 'verbose_name': 'Variável da Etapa', 'verbose_name_plural': 'Variáveis da Etapa'},
        ),
        migrations.AlterModelOptions(
            name='scheduledremindervariable',
            options={'ordering': ['component', 'index'], 'verbose_name': 'Variável do Lembrete', 'verbose_name_plural': 'Variáveis do Lembrete'},
        ),
        migrations.AlterUniqueTogether(
            name='collectionstepvariable',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledremindervariable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='collectionstepvariable',
            name='component',
            field=models.CharField(choices=[('BODY', 'Corpo'), ('BUTTON', 'Botão')], default='BODY', max_length=10, verbose_name='Componente'),
        ),
        migrations.AddField(
            model_name='scheduledremindervariable',
            name='component',
            field=models.CharField(choices=[('BODY', 'Corpo'), ('BUTTON', 'Botão')], default='BODY', max_length=10, verbose_name='Componente'),
        ),
        migrations.AlterField(
            model_name='collectionstepvariable',
            name='index',
            field=models.PositiveIntegerField(verbose_name='Índice'),
        ),
        migrations.AlterField(
            model_name='scheduledremindervariable',
            name='index',
            field=models.PositiveIntegerField(verbose_name='Índice'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionstepvariable',
            unique_together={('step', 'component', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='scheduledremindervariable',
            unique_together={('reminder', 'component', 'index')},
        ),
    ]
