# Generated by Django 5.2.12 on 2026-06-25 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0022_add_component_to_step_and_reminder_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualMessageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('ENVIO_ORCAMENTO', 'Envio de Orçamento')], max_length=50, unique=True, verbose_name='Gatilho')),
                ('template_name', models.CharField(max_length=100, verbose_name='Template WhatsApp (Meta)')),
                ('header_media_type', models.CharField(choices=[('NONE', 'Sem mídia'), ('BUDGET_PDF', 'PDF do Orçamento (gerado dinamicamente)'), ('STATIC_PDF', 'PDF Estático (upload)')], default='NONE', max_length=20, verbose_name='Mídia do Cabeçalho')),
                ('static_media_file', models.FileField(blank=True, null=True, upload_to='manual_messages/static/', verbose_name='Arquivo Estático')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensagem Manual',
                'verbose_name_plural': 'Mensagens Manuais',
            },
        ),
        migrations.CreateModel(
            name='ManualMessageVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='Índice')),
                ('field_path', models.CharField(max_length=255, verbose_name='Caminho do Campo')),
                ('component', models.CharField(choices=[('BODY', 'Corpo'), ('BUTTON', 'Botão')], default='BODY', max_length=10, verbose_name='Componente')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='integracoes.manualmessageconfig')),
            ],
            options={
                'verbose_name': 'Variável de Mensagem Manual',
                'verbose_name_plural': 'Variáveis de Mensagens Manuais',
                'ordering': ['component', 'index'],
                'unique_together': {('config', 'component', 'index')},
            },
        ),
    ]
