# Generated by Django 5.2.12 on 2026-07-07 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0023_add_manual_message_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushinPaySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=100, verbose_name='ID da Assinatura (PushinPay)')),
                ('first_charge_id', models.CharField(blank=True, max_length=100, verbose_name='ID da Primeira Cobrança')),
                ('status', models.CharField(choices=[('NAO_CRIADA', 'Não criada'), ('AGUARDANDO_PRIMEIRO_PAGAMENTO', 'Aguardando primeiro pagamento'), ('ATIVA', 'Ativa'), ('ATRASADA', 'Atrasada'), ('CANCELADA', 'Cancelada')], default='NAO_CRIADA', max_length=40, verbose_name='Status')),
                ('qr_code', models.TextField(blank=True, verbose_name='Pix Copia e Cola')),
                ('qr_code_base64', models.TextField(blank=True, verbose_name='QR Code (base64)')),
                ('value_cents', models.PositiveIntegerField(default=0, verbose_name='Valor (centavos)')),
                ('frequency', models.CharField(blank=True, max_length=50, verbose_name='Periodicidade')),
                ('retry_policy', models.PositiveIntegerField(default=0, verbose_name='Política de Retentativas')),
                ('last_event_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Evento em')),
                ('status_detail', models.TextField(blank=True, help_text='Avisos, ex: evento de webhook não reconhecido — revisar manualmente', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assinatura da Plataforma',
                'verbose_name_plural': 'Assinatura da Plataforma',
            },
        ),
        migrations.AlterField(
            model_name='manualmessageconfig',
            name='trigger',
            field=models.CharField(choices=[('ENVIO_ORCAMENTO', 'Envio de Orçamento'), ('CONVITE_CADASTRO', 'Convite para Cadastro')], max_length=50, unique=True, verbose_name='Gatilho'),
        ),
        migrations.CreateModel(
            name='PushinPaySubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(blank=True, max_length=100, verbose_name='ID da Cobrança')),
                ('raw_event', models.CharField(blank=True, max_length=100, verbose_name='Evento (bruto)')),
                ('mapped_status', models.CharField(blank=True, choices=[('NAO_CRIADA', 'Não criada'), ('AGUARDANDO_PRIMEIRO_PAGAMENTO', 'Aguardando primeiro pagamento'), ('ATIVA', 'Ativa'), ('ATRASADA', 'Atrasada'), ('CANCELADA', 'Cancelada')], max_length=40, verbose_name='Status Mapeado')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload Bruto')),
                ('headers', models.JSONField(blank=True, null=True, verbose_name='Cabeçalhos')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='integracoes.pushinpaysubscription')),
            ],
            options={
                'verbose_name': 'Evento da Assinatura',
                'verbose_name_plural': 'Eventos da Assinatura',
                'ordering': ['-created_at'],
            },
        ),
    ]
