# Generated by Django 5.2.12 on 2026-07-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0025_rename_to_platform_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsubscription',
            name='next_due_date',
            field=models.DateField(blank=True, help_text='Data de vencimento da cobrança do ciclo em aberto, conforme o Asaas', null=True, verbose_name='Vencimento do Ciclo Atual'),
        ),
    ]
