# Generated by Django 5.2.12 on 2026-07-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0026_platformsubscription_next_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('value_cents', models.PositiveIntegerField(verbose_name='Valor (centavos)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (Pix não gerado)'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGA', 'Paga'), ('ATRASADA', 'Atrasada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=30, verbose_name='Status')),
                ('asaas_charge_id', models.CharField(blank=True, max_length=100, verbose_name='ID da Cobrança (Asaas)')),
                ('qr_code', models.TextField(blank=True, verbose_name='Pix Copia e Cola')),
                ('qr_code_base64', models.TextField(blank=True, verbose_name='QR Code (base64)')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fatura da Plataforma',
                'verbose_name_plural': 'Faturas da Plataforma',
                'ordering': ['due_date'],
            },
        ),
    ]
