# Generated by Django 5.2.12 on 2026-07-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0027_platforminvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationconfig',
            name='chatwoot_tag',
            field=models.CharField(blank=True, help_text='Etiqueta aplicada à conversa no Chatwoot ao enviar esta notificação. Criada automaticamente se não existir. Deixe em branco para não aplicar nenhuma tag.', max_length=50, null=True, verbose_name='Tag do Chatwoot'),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='chatwoot_tag_mode',
            field=models.CharField(choices=[('ADD', 'Adicionar às existentes'), ('REPLACE', 'Substituir existentes')], default='ADD', help_text='Se a tag deve ser adicionada junto às etiquetas já existentes na conversa, ou substituir todas as etiquetas atuais.', max_length=10, verbose_name='Modo da Tag'),
        ),
    ]
