# Generated by Django 5.2.12 on 2026-07-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0028_notificationconfig_chatwoot_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsequence',
            name='date_range_end',
            field=models.DateField(blank=True, help_text='Se preenchido, a régua só considera parcelas com vencimento até esta data. Se ambos os campos ficarem em branco, considera parcelas de qualquer vencimento.', null=True, verbose_name='Fim do Intervalo de Vencimento'),
        ),
        migrations.AddField(
            model_name='collectionsequence',
            name='date_range_start',
            field=models.DateField(blank=True, help_text='Se preenchido, a régua só considera parcelas com vencimento a partir desta data.', null=True, verbose_name='Início do Intervalo de Vencimento'),
        ),
    ]
