# Generated by Django 5.2.12 on 2026-07-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0029_collectionsequence_date_range_end_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionstep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='collectionstep',
            name='applies_to',
            field=models.CharField(choices=[('ANY', 'Qualquer cobrança'), ('COM_GATEWAY', 'Somente com cobrança no gateway (Pix/Boleto automático)'), ('SEM_GATEWAY', 'Somente sem cobrança no gateway (pagamento manual)')], default='ANY', help_text='Um template com botão de Pix/copiar código não pode ser reaproveitado para parcelas sem cobrança no gateway (o botão é fixo no template aprovado pela Meta). Cadastre duas etapas para a mesma ocorrência — uma "Somente com gateway" e outra "Somente sem gateway" — para usar templates diferentes conforme o caso. Deixe "Qualquer cobrança" se o mesmo template serve para os dois casos.', max_length=15, verbose_name='Aplica-se a'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionstep',
            unique_together={('sequence', 'occurrence', 'applies_to')},
        ),
    ]
