# Generated by Django 5.2.12 on 2026-07-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0030_alter_collectionstep_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreminder',
            name='anchor_field',
            field=models.CharField(choices=[('due_date', 'Vencimento'), ('discount_deadline', 'Limite do Desconto')], default='due_date', help_text='Campo de Installment usado como base para o offset em dias.', max_length=20, verbose_name='Data de Referência'),
        ),
        migrations.AlterField(
            model_name='scheduledreminder',
            name='offset_days',
            field=models.IntegerField(default=-1, help_text='Negativo = antes da data de referência (ex: -1 = 1 dia antes), 0 = no dia, positivo = após', verbose_name='Offset em Dias'),
        ),
    ]
