# Generated by Django 5.2.12 on 2026-07-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0031_scheduledreminder_anchor_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreminder',
            name='payment_channel',
            field=models.CharField(choices=[('ANY', 'Qualquer'), ('PIX', 'Pix (gateway ativo)'), ('BOLETO', 'Boleto (gateway ativo)'), ('SEM_GATEWAY', 'Sem gateway (dinheiro/manual)')], default='ANY', help_text='Restringe o disparo às parcelas com esse canal — evita mandar variável de template (ex: código Pix) em branco para quem paga por outro meio.', max_length=15, verbose_name='Canal de Pagamento'),
        ),
    ]
