# Generated by Django 5.2.12 on 2026-08-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0032_scheduledreminder_payment_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsequence',
            name='billing_source',
            field=models.CharField(choices=[('ANY', 'Qualquer origem'), ('VENDA', 'Somente Vendas'), ('SERVICO', 'Somente Serviços')], default='ANY', help_text='Filtra as cobranças por origem (Vendas, Serviços ou Qualquer).', max_length=20, verbose_name='Origem da Cobrança'),
        ),
    ]
