# Generated by Django 5.2.12 on 2026-09-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0033_collectionsequence_billing_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='technician_can_view_order_values',
            field=models.BooleanField(default=True, help_text='Permite exibir preços, totais e saldo das ordens de serviço no app do técnico.', verbose_name='Técnicos podem visualizar valores das OSs'),
        ),
    ]
