# Generated by Django 5.2.12 on 2026-09-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0034_systemconfig_technician_can_view_order_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationconfig',
            name='sale_type_filter',
            field=models.CharField(blank=True, choices=[('PRESENCIAL', 'Venda presencial'), ('DISTANCIA', 'Venda à distância')], default='', help_text='Deixe vazio para disparar em todos os tipos de venda.', max_length=20, verbose_name='Filtro por Tipo de Venda'),
        ),
    ]
