upstream django_app {
    server web:8001;
}

# Redirecionar HTTP para HTTPS
server {
    listen 80;
    server_name osonline.douradoscalhas.com.br;
    
    # Location para validação do Certbot (renovação automática)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    # Redirecionar todo o resto para HTTPS
    location / {
        return 301 https://$server_name$request_uri;
    }
}

# Servidor HTTPS
server {
    listen 443 ssl http2;
    server_name osonline.douradoscalhas.com.br;

    # Certificados SSL
    ssl_certificate /etc/letsencrypt/live/osonline.douradoscalhas.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/osonline.douradoscalhas.com.br/privkey.pem;
    
    # Configurações SSL recomendadas
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    
    # Aumentar limite de upload se necessário (ex: 20M)
    client_max_body_size 50M;

    location / {
        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_redirect off;
    }

    # Serve os arquivos estáticos diretamente pelo NGINX
    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Serve os arquivos de media (uploads, vídeos, imagens)
    location /media/ {
        alias /app/media/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}

